## Port of tools/codegen/src/world_event.rs - emits the `WorldEvent` enum
## with explicit u16 discriminants from `assets/world_event.json` (a
## name->id map), sorted like upstream's `BTreeMap` iteration order.

import std/syncio
import codegenutil

const OutPath = "src/generated/world_event.nim"

proc build(assetsPath: string): string =
  let events = readStringIntMapSorted(assetsPath & "/world_event.json")

  result = "## GENERATED by src/data_codegen/gen_world_event.nim - do not edit by hand.\n\n"
  result.add("type\n  WorldEvent* = enum\n")
  for (name, id) in events:
    result.add("    we" & toPascalCase(name) & " = " & $id & "\n")

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
