## Proof-of-concept Nimony port of tools/codegen/src/sound_category.rs
## - the smallest of codegen's ~90 generator submodules, picked to
## establish the pattern the rest should follow.
##
## Rust's version reads `../../assets/sound_category.json` and builds a
## `proc_macro2::TokenStream` via `quote!{...}` (real Rust AST nodes,
## eventually pretty-printed by rustfmt). Nimony has no macro/quote
## equivalent for emitting *its own* source - and doesn't need one: this
## just builds the output as a plain string and writes it to a .nim file.
## That's the general shape every other codegen/src/*.rs module
## should follow once ported: JSON in (via std/json, confirmed present in
## Nimony's stdlib), formatted Nim source text out.
##
## Run with `nimony c -r src/data_codegen/gen_sound_category.nim` from the
## repo root (it locates ../upstream-ref/assets relative to this repo's
## parent directory - see `assetsPath` below).

import std/[syncio, json, strutils]

const OutPath = "src/generated/sound_category.nim"

proc toPascalCase(s: string): string =
  ## Port of `heck::ToPascalCase` as codegen uses it here: splits on
  ## `_`/`-`/whitespace, uppercases each word's first letter, lowercases the
  ## rest, concatenates. Input here is SCREAMING_SNAKE JSON values like
  ## "MASTER", "RECORDS" - e.g. "MASTER" -> "Master".
  result = ""
  var capitalizeNext = true
  for ch in s:
    if ch == '_' or ch == '-' or ch == ' ':
      capitalizeNext = true
    elif capitalizeNext:
      result.add(toUpperAscii(ch))
      capitalizeNext = false
    else:
      result.add(toLowerAscii(ch))

proc build(assetsPath: string): string =
  var tree = parseFile(assetsPath & "/sound_category.json")
  let arr = root(tree)
  var categories: seq[string] = @[]
  for elem in arr:
    categories.add(elem.getStr())

  var s = "## GENERATED by src/data_codegen/gen_sound_category.nim - do not edit by hand.\n\n"
  s.add("type\n  SoundCategory* = enum\n")
  for cat in categories:
    s.add("    sc" & toPascalCase(cat) & "\n")
  s.add("\n")

  s.add("proc soundCategoryFromName*(name: string): (bool, SoundCategory) =\n")
  s.add("  case name\n")
  for cat in categories:
    s.add("  of \"" & toLowerAscii(cat) & "\": (true, sc" & toPascalCase(cat) & ")\n")
  s.add("  else: (false, sc" & toPascalCase(categories[0]) & ")\n\n")

  s.add("proc soundCategoryToName*(c: SoundCategory): string =\n")
  s.add("  case c\n")
  for cat in categories:
    s.add("  of sc" & toPascalCase(cat) & ": \"" & toLowerAscii(cat) & "\"\n")

  s

when isMainModule:
  # the upstream reference clone is a sibling of this repo: C:\Users\savant\Projects\{upstream-ref,minecraft-server}
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
