## Generator for `DyeColor`.
## Port of upstream/tools/codegen/src/dye_color.rs

import std/[syncio, json]
import codegenutil

type
  DyeColorEntry = object
    id, mapColorId, terracottaColorId: int
    texDiffuse, fireworkColor, textColor: int
    name: string

proc readDyeColors(path: string): seq[DyeColorEntry] =
  ## Port of `serde_json::from_str::<Vec<DyeColorEntry>>(...)` for
  ## dye_colors.json's flat `[{id,name,map_color_id,terracotta_color_id,
  ## texture_diffuse_color,firework_color,text_color}, ...]` shape.
  var tree = parseFile(path)
  let arr = root(tree)
  result = @[]
  for elem in arr:
    var e = DyeColorEntry(id: 0, mapColorId: 0, terracottaColorId: 0,
      texDiffuse: 0, fireworkColor: 0, textColor: 0, name: "")
    for key, val in elem.pairs():
      case key
      of "id": e.id = int(val.getInt())
      of "name": e.name = val.getStr()
      of "map_color_id": e.mapColorId = int(val.getInt())
      of "terracotta_color_id": e.terracottaColorId = int(val.getInt())
      of "texture_diffuse_color": e.texDiffuse = int(val.getInt())
      of "firework_color": e.fireworkColor = int(val.getInt())
      of "text_color": e.textColor = int(val.getInt())
      else: discard
    result.add(e)

proc main() =
  let colors = readDyeColors("../upstream-ref/assets/dye_colors.json")

  var variants = ""
  var idArms = ""
  var nameArms = ""
  var byIdArms = ""
  var byNameArms = ""
  var mapColorIdArms = ""
  var terracottaColorIdArms = ""
  var texDiffuseArms = ""
  var fireworkColorArms = ""
  var textColorArms = ""

  for e in colors:
    let v = toPascalCase(e.name)
    variants.add("    dc" & v & "\n")
    idArms.add("  of dc" & v & ": " & $e.id & "\n")
    nameArms.add("  of dc" & v & ": \"" & e.name & "\"\n")
    byIdArms.add("  of " & $e.id & ": (true, dc" & v & ")\n")
    byNameArms.add("  of \"" & e.name & "\": (true, dc" & v & ")\n")
    mapColorIdArms.add("  of dc" & v & ": " & $e.mapColorId & "\n")
    terracottaColorIdArms.add("  of dc" & v & ": " & $e.terracottaColorId & "\n")
    texDiffuseArms.add("  of dc" & v & ": " & $e.texDiffuse & "'u32\n")
    fireworkColorArms.add("  of dc" & v & ": " & $e.fireworkColor & "'u32\n")
    textColorArms.add("  of dc" & v & ": " & $e.textColor & "'u32\n")

  # upstream defaults to black (via #[default]) when a lookup fails.
  let defaultConst = "dcBlack"

  let output = "## The `DyeColor` registry.\n" &
    "## Generated by gen_dye_color.nim from upstream/assets/dye_colors.json - do not edit by hand.\n\n" &
    "type\n" &
    "  DyeColor* = enum\n" &
    variants & "\n" &
    "proc id*(c: DyeColor): int =\n" &
    "  case c\n" & idArms & "\n" &
    "proc name*(c: DyeColor): string =\n" &
    "  case c\n" & nameArms & "\n" &
    "proc mapColorId*(c: DyeColor): int =\n" &
    "  case c\n" & mapColorIdArms & "\n" &
    "proc terracottaColorId*(c: DyeColor): int =\n" &
    "  case c\n" & terracottaColorIdArms & "\n" &
    "proc textureDiffuseColor*(c: DyeColor): uint32 =\n" &
    "  case c\n" & texDiffuseArms & "\n" &
    "proc fireworkColor*(c: DyeColor): uint32 =\n" &
    "  case c\n" & fireworkColorArms & "\n" &
    "proc textColor*(c: DyeColor): uint32 =\n" &
    "  case c\n" & textColorArms & "\n" &
    "proc byId*(id: int): (bool, DyeColor) =\n" &
    "  case id\n" & byIdArms &
    "  else: (false, " & defaultConst & ")\n\n" &
    "proc byName*(name: string): (bool, DyeColor) =\n" &
    "  case name\n" & byNameArms &
    "  else: (false, " & defaultConst & ")\n\n" &
    "proc dyeColorFromIdOrDefault*(id: int): DyeColor =\n" &
    "  ## Port of `impl From<u8> for DyeColor` / `From<i8>`: falls back to\n" &
    "  ## Black (upstream's #[default]) instead of failing.\n" &
    "  let (ok, c) = byId(id)\n" &
    "  if ok: c else: " & defaultConst & "\n"

  try:
    writeFile("src/generated/dye_color.nim", output)
  except ErrorCode as e:
    echo "write failed: " & $e
  echo "wrote src/generated/dye_color.nim (" & $colors.len & " colors)"

main()
