## Generator for `Sound`.
## Port of upstream/tools/codegen/src/sound.rs

import std/syncio
import codegenutil

proc main() =
  let sounds = readStringArray("../upstream-ref/assets/sounds.json")

  var variants = ""
  var fromNameArms = ""
  var toNameArms = ""

  for i, name in sounds:
    let v = "sd" & toPascalCase(name)
    variants.add("    " & v & "\n")
    fromNameArms.add("  of \"" & name & "\": (true, " & v & ")\n")
    toNameArms.add("  of " & v & ": \"" & name & "\"\n")

  let firstVariant = if sounds.len > 0: "sd" & toPascalCase(sounds[0]) else: "sdNone"

  let output = "## The `Sound` registry (id = declaration/array order, matching\n" &
    "## upstream's #[repr(u16)] enum).\n" &
    "## Generated by gen_sound.nim from upstream/assets/sounds.json - do not edit by hand.\n\n" &
    "type\n" &
    "  Sound* = enum\n" &
    variants & "\n" &
    "proc fromName*(name: string): (bool, Sound) =\n" &
    "  case name\n" & fromNameArms &
    "  else: (false, " & firstVariant & ")\n\n" &
    "proc toName*(s: Sound): string =\n" &
    "  case s\n" & toNameArms

  try:
    writeFile("src/generated/sound.nim", output)
  except ErrorCode as e:
    echo "write failed: " & $e
  echo "wrote src/generated/sound.nim (" & $sounds.len & " sounds)"

main()
