## Port of tools/codegen/src/slot_ranges.rs (69 lines).
##
## Reads `assets/slot_ranges.json` (a `BTreeMap<String, Box<[usize]>>` of
## named inventory slot-index ranges, e.g. `"container.0": [0]`) and emits
## the name->range table plus the two derived name lists upstream builds:
## every range name, and just the names whose range is a single slot.
## Upstream matches on the literal string keys directly (no enum), so this
## does the same rather than inventing one.
##
## Run with `nimony c -r src/data_codegen/gen_slot_ranges.nim` from the
## repo root.

import std/[syncio, strutils]
import codegenutil

const OutPath = "src/generated/slot_ranges.nim"

proc rangeLit(nums: seq[int]): string =
  result = "@["
  for i, n in nums:
    if i > 0: result.add(", ")
    result.add($n)
  result.add("]")

proc build(assetsPath: string): string =
  let ranges = readStringIntSeqMapSorted(assetsPath & "/slot_ranges.json")

  var s = "## GENERATED by src/data_codegen/gen_slot_ranges.nim - do not edit by hand.\n\n"

  s.add("proc slotRanges*(): seq[(string, seq[int])] =\n")
  s.add("  @[\n")
  for (name, nums) in ranges:
    s.add("    (\"" & name & "\", " & rangeLit(nums) & "),\n")
  s.add("  ]\n\n")

  s.add("proc slotRangeAllNames*(): seq[string] =\n")
  s.add("  @[")
  for i, (name, _) in ranges:
    if i > 0: s.add(", ")
    s.add("\"" & name & "\"")
  s.add("]\n\n")

  s.add("proc slotRangeSingleSlotNames*(): seq[string] =\n")
  s.add("  @[")
  var first = true
  for (name, nums) in ranges:
    if nums.len == 1:
      if not first: s.add(", ")
      s.add("\"" & name & "\"")
      first = false
  s.add("]\n\n")

  s.add("proc getSlotRange*(name: string): (bool, seq[int]) =\n")
  s.add("  case name\n")
  for (name, nums) in ranges:
    s.add("  of \"" & name & "\": (true, " & rangeLit(nums) & ")\n")
  s.add("  else: (false, @[])\n")

  s

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
