## Port of tools/codegen/src/map_decoration.rs. A single JSON array of
## objects (`map_decorations.json`), positional (not a directory or
## name-keyed map like most other generators) - id is the array index.
## `map_color` defaults to -1 and `exploration_map_element` defaults to
## false when absent, matching upstream's `#[serde(default = ...)]`/
## `#[serde(default)]`.
##
## Run with `nimony c -r src/data_codegen/gen_map_decoration.nim` from the
## repo root.

import std/[json, syncio, paths]
import codegenutil

const OutPath = "src/generated/map_decoration.nim"

type
  MapDecorationEntry = object
    name, assetName: string
    showOnItemFrame: bool
    mapColor: int
    explorationMapElement: bool
    trackCount: bool

proc readEntries(jsonPath: string): seq[MapDecorationEntry] =
  var tree = parseFile(jsonPath)
  let arr = root(tree)
  result = @[]
  for elem in arr:
    var e = MapDecorationEntry(name: "", assetName: "", showOnItemFrame: false,
      mapColor: -1, explorationMapElement: false, trackCount: false)
    for key, val in elem.pairs():
      case key
      of "name": e.name = val.getStr()
      of "asset_name": e.assetName = val.getStr()
      of "show_on_item_frame": e.showOnItemFrame = val.getBool()
      of "map_color": e.mapColor = int(val.getInt())
      of "exploration_map_element": e.explorationMapElement = val.getBool()
      of "track_count": e.trackCount = val.getBool()
      else: discard
    result.add(e)

proc build(jsonPath: string): string =
  let entries = readEntries(jsonPath)

  var s = "## GENERATED by src/data_codegen/gen_map_decoration.nim - do not edit by hand.\n\n"
  s.add("type\n  MapDecorationType* = object\n")
  s.add("    id*: uint32\n    name*, assetName*: string\n")
  s.add("    showOnItemFrame*: bool\n    mapColor*: int32\n")
  s.add("    explorationMapElement*: bool\n    trackCount*: bool\n\n")

  for i, e in entries:
    s.add("const " & toShoutySnakeCase(e.name) & "* = MapDecorationType(id: " & $i &
      "'u32, name: \"" & e.name & "\", assetName: \"" & e.assetName &
      "\", showOnItemFrame: " & (if e.showOnItemFrame: "true" else: "false") &
      ", mapColor: " & $e.mapColor & "'i32, explorationMapElement: " &
      (if e.explorationMapElement: "true" else: "false") &
      ", trackCount: " & (if e.trackCount: "true" else: "false") & ")\n")
  s.add("\n")

  s.add("const AllMapDecorations*: array[" & $entries.len & ", MapDecorationType] = [\n")
  for e in entries:
    s.add("  " & toShoutySnakeCase(e.name) & ",\n")
  s.add("]\n\n")

  s.add("proc mapDecorationFromId*(id: uint32): (bool, MapDecorationType) =\n")
  s.add("  if id < " & $entries.len & "'u32:\n")
  s.add("    result = (true, AllMapDecorations[int(id)])\n")
  s.add("  else:\n")
  s.add("    result = (false, AllMapDecorations[0])\n\n")

  s.add("proc mapDecorationFromName*(name: string): (bool, MapDecorationType) =\n")
  s.add("  case name\n")
  for e in entries:
    s.add("  of \"" & e.name & "\": (true, " & toShoutySnakeCase(e.name) & ")\n")
  s.add("  else: (false, AllMapDecorations[0])\n")

  s

when isMainModule:
  try:
    let generated = build("../upstream-ref/assets/map_decorations.json")
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
