## Port of upstream/tools/pumpkin-codegen/src/entity_type.rs.
##
## Reads assets/entities.json (a name -> entry map) and emits
## src/generated/entity_type.nim: an `EntityType` object per entity plus a
## `byName` lookup. Scoped down from upstream's full struct: the
## `attributes: &'static [(Attributes, f64)]` field and the nested
## `SpawnRestriction`/`HeightMap`/`SpawnLocation` enums are skipped -
## `attributes` because it needs per-entry map-decoding logic upstream
## builds via `map.iter().next().unwrap()` per attribute entry (one
## extra layer of nesting this pass didn't scope in), and spawn
## restriction because it's natural-spawn-placement logic irrelevant to
## the dimension/hitbox data this generator exists to unblock (entity.nim's
## `EntityDimensions`, and the concrete entities that currently hand-write
## their own dimension values). `hurtSound`/`deathSound` are kept as plain
## sound-name strings rather than linked to `src/generated/sound.nim`'s
## `Sound` enum, to avoid this generator depending on that module's exact
## variant-naming scheme; a future pass can resolve them once needed.

import std/[json, paths, algorithm, syncio]
import codegenutil

type
  EntityTypeEntry = object
    id: int
    mob: bool
    hasMob: bool
    saveable: bool
    summonable: bool
    fireImmune: bool
    canSpawnFarFromPlayer: bool
    trackDeltas: bool
    clientTrackingRange: int
    updateInterval: int
    limitPerChunk: int
    hasLimitPerChunk: bool
    dimensionW: float
    dimensionH: float
    eyeHeight: float
    spawnDimensionsScale: float
    experienceReward: int
    hurtSound: string
    hasHurtSound: bool
    deathSound: string
    hasDeathSound: bool
    attackable: bool
    hasAttackable: bool

proc readEntities(path: string): seq[(string, EntityTypeEntry)] =
  var tree = parseFile(path)
  let obj = root(tree)
  result = @[]
  for name, val in obj.pairs():
    var e = EntityTypeEntry(id: 0, mob: false, hasMob: false, saveable: false,
      summonable: false, fireImmune: false, canSpawnFarFromPlayer: false,
      trackDeltas: false, clientTrackingRange: 0, updateInterval: 0,
      limitPerChunk: 0, hasLimitPerChunk: false, dimensionW: 0.0,
      dimensionH: 0.0, eyeHeight: 0.0, spawnDimensionsScale: 1.0,
      experienceReward: 0, hurtSound: "", hasHurtSound: false,
      deathSound: "", hasDeathSound: false, attackable: false,
      hasAttackable: false)
    for key, v in val.pairs():
      case key
      of "id": e.id = int(v.getInt())
      of "mob":
        e.mob = v.getBool()
        e.hasMob = true
      of "saveable": e.saveable = v.getBool()
      of "summonable": e.summonable = v.getBool()
      of "fire_immune": e.fireImmune = v.getBool()
      of "can_spawn_far_from_player": e.canSpawnFarFromPlayer = v.getBool()
      of "track_deltas": e.trackDeltas = v.getBool()
      of "client_tracking_range": e.clientTrackingRange = int(v.getInt())
      of "update_interval": e.updateInterval = int(v.getInt())
      of "limit_per_chunk":
        e.limitPerChunk = int(v.getInt())
        e.hasLimitPerChunk = true
      of "dimension":
        var dims: seq[float] = @[]
        for d in v.items():
          dims.add(d.getFloat())
        if dims.len >= 2:
          e.dimensionW = dims[0]
          e.dimensionH = dims[1]
      of "eye_height": e.eyeHeight = v.getFloat()
      of "spawn_dimensions_scale": e.spawnDimensionsScale = v.getFloat()
      of "experience_reward": e.experienceReward = int(v.getInt())
      of "hurt_sound":
        e.hurtSound = v.getStr()
        e.hasHurtSound = true
      of "death_sound":
        e.deathSound = v.getStr()
        e.hasDeathSound = true
      of "attackable":
        e.attackable = v.getBool()
        e.hasAttackable = true
      else: discard
    result.add((name, e))
  result.sort(proc(a, b: (string, EntityTypeEntry)): int =
    cmp(a[0], b[0]))

proc quoteStr(s: string): string =
  "\"" & s & "\""

proc genEntityType(entries: seq[(string, EntityTypeEntry)]): string =
  result = "## Generated by gen_entity_type.nim from assets/entities.json. Do not edit.\n\n"
  result.add("type\n")
  result.add("  EntityType* = object\n")
  result.add("    id*: uint16\n")
  result.add("    name*: string\n")
  result.add("    mob*: bool\n")
  result.add("    saveable*: bool\n")
  result.add("    summonable*: bool\n")
  result.add("    fireImmune*: bool\n")
  result.add("    canSpawnFarFromPlayer*: bool\n")
  result.add("    trackDeltas*: bool\n")
  result.add("    clientTrackingRange*: uint32\n")
  result.add("    updateInterval*: uint32\n")
  result.add("    limitPerChunk*: int32\n")
  result.add("    dimensionW*: float32\n")
  result.add("    dimensionH*: float32\n")
  result.add("    eyeHeight*: float32\n")
  result.add("    spawnDimensionsScale*: float32\n")
  result.add("    experienceReward*: uint32\n")
  result.add("    hurtSound*: string\n")
  result.add("    deathSound*: string\n")
  result.add("    attackableKnown*: bool\n")
  result.add("    attackable*: bool\n\n")

  result.add("proc allEntityTypes*(): seq[EntityType] =\n")
  result.add("  result = @[]\n")
  for (name, e) in entries:
    var line = "  result.add(EntityType(id: " & $e.id & "'u16, name: " & quoteStr(name) &
      ", mob: " & $e.mob & ", saveable: " & $e.saveable &
      ", summonable: " & $e.summonable & ", fireImmune: " & $e.fireImmune &
      ", canSpawnFarFromPlayer: " & $e.canSpawnFarFromPlayer &
      ", trackDeltas: " & $e.trackDeltas &
      ", clientTrackingRange: " & $e.clientTrackingRange & "'u32" &
      ", updateInterval: " & $e.updateInterval & "'u32" &
      ", limitPerChunk: " & $e.limitPerChunk & "'i32" &
      ", dimensionW: " & $e.dimensionW & "'f32" &
      ", dimensionH: " & $e.dimensionH & "'f32" &
      ", eyeHeight: " & $e.eyeHeight & "'f32" &
      ", spawnDimensionsScale: " & $e.spawnDimensionsScale & "'f32" &
      ", experienceReward: " & $e.experienceReward & "'u32" &
      ", hurtSound: " & quoteStr(e.hurtSound) &
      ", deathSound: " & quoteStr(e.deathSound) &
      ", attackableKnown: " & $e.hasAttackable &
      ", attackable: " & $e.attackable & "))\n"
    result.add(line)

  result.add("\nproc entityTypeByName*(name: string): (bool, EntityType) =\n")
  result.add("  let all = allEntityTypes()\n")
  result.add("  for e in all:\n")
  result.add("    if e.name == name:\n")
  result.add("      return (true, e)\n")
  result.add("  (false, EntityType())\n")

when isMainModule:
  const OutPath = "src/generated/entity_type.nim"
  let entries = readEntities("../upstream-ref/assets/entities.json")
  let src = genEntityType(entries)
  try:
    writeFile(OutPath, src)
  except ErrorCode as e:
    echo "writeFile failed: " & $e
  echo "wrote " & OutPath & " with " & $entries.len & " entity types"
