## Generator for `JukeboxSong`.
## Port of upstream/tools/codegen/src/jukebox_song.rs

import std/[syncio, paths]
import codegenutil

proc variantIdent(stem: string): string =
  let pascal = toPascalCase(stem)
  if pascal.len > 0 and isAsciiDigit(pascal[0]): "Id" & pascal
  else: pascal

proc main() =
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/jukebox_song")
  let entries = listJsonStems(dir)

  var variants = ""
  var fromNameArms = ""
  var toNameArms = ""
  var toIdArms = ""
  var toComparatorArms = ""
  var toLengthArms = ""

  for i, (stem, path) in entries:
    let v = "js" & variantIdent(stem)
    let lengthSecs = jsonFloatField(path, "length_in_seconds", 0.0)
    let comparator = jsonIntField(path, "comparator_output", 0)

    variants.add("    " & v & "\n")
    fromNameArms.add("  of \"" & stem & "\": (true, " & v & ")\n")
    toNameArms.add("  of " & v & ": \"" & stem & "\"\n")
    toIdArms.add("  of " & v & ": " & $i & "'u32\n")
    toComparatorArms.add("  of " & v & ": " & $comparator & "'u8\n")
    toLengthArms.add("  of " & v & ": " & $int(lengthSecs) & "'u32\n")

  let firstVariant =
    if entries.len > 0: "js" & variantIdent(entries[0][0])
    else: "jsNone"

  let output = "## The `JukeboxSong` registry.\n" &
    "## Generated by gen_jukebox_song.nim from upstream/assets/datapack/data/minecraft/jukebox_song/ - do not edit by hand.\n\n" &
    "type\n" &
    "  JukeboxSong* = enum\n" &
    variants & "\n" &
    "proc fromName*(name: string): (bool, JukeboxSong) =\n" &
    "  case name\n" & fromNameArms &
    "  else: (false, " & firstVariant & ")\n\n" &
    "proc toName*(s: JukeboxSong): string =\n" &
    "  case s\n" & toNameArms & "\n" &
    "proc getId*(s: JukeboxSong): uint32 =\n" &
    "  case s\n" & toIdArms & "\n" &
    "proc comparatorOutput*(s: JukeboxSong): uint8 =\n" &
    "  case s\n" & toComparatorArms & "\n" &
    "proc lengthInSeconds*(s: JukeboxSong): uint32 =\n" &
    "  case s\n" & toLengthArms & "\n" &
    "proc lengthInTicks*(s: JukeboxSong): uint64 =\n" &
    "  uint64(lengthInSeconds(s)) * 20'u64\n"

  try:
    writeFile("src/generated/jukebox_song.nim", output)
  except ErrorCode as e:
    echo "write failed: " & $e
  echo "wrote src/generated/jukebox_song.nim (" & $entries.len & " songs)"

main()
