## Port of tools/codegen/src/damage_type.rs (206 lines).
##
## Reads one JSON file per damage type from
## `assets/datapack/data/minecraft/damage_type/` (directory-of-JSON-files
## shape, same as decorated_pot_pattern/cat_variant/banner_pattern/etc.)
## and emits a `DamageType` object + one named constant per entry (id =
## sorted directory order), plus `fromName`/`fromId` lookups.
##
## `death_message_type`/`effects` are optional string enums (default
## "default"/absent respectively); `exhaustion`/`message_id`/`scaling` are
## required. Upstream's `Taggable` impl (registry-tag lookup) is skipped -
## it needs `tag.rs`'s `RegistryKey`/`Tag` machinery, unported.
##
## Run with `nimony c -r src/data_codegen/gen_damage_type.nim` from the
## repo root.

import std/[syncio, strutils, paths]
import codegenutil

const OutPath = "src/generated/damage_type.nim"

type
  DamageEntry = object
    name: string
    deathMessageType: string ## "" -> Default
    exhaustion: float
    effects: string ## "" -> None
    messageId: string
    scaling: string

proc build(assetsPath: string): string =
  let dir = path(assetsPath & "/datapack/data/minecraft/damage_type")
  let stems = listJsonStems(dir)
  var entries: seq[DamageEntry] = @[]
  for (stem, jsonPath) in stems:
    entries.add(DamageEntry(
      name: stem,
      deathMessageType: jsonStringField(jsonPath, "death_message_type"),
      exhaustion: jsonFloatField(jsonPath, "exhaustion", 0.0),
      effects: jsonStringField(jsonPath, "effects"),
      messageId: jsonStringField(jsonPath, "message_id"),
      scaling: jsonStringField(jsonPath, "scaling"),
    ))

  var s = "## GENERATED by src/data_codegen/gen_damage_type.nim - do not edit by hand.\n\n"

  s.add("type\n")
  s.add("  DeathMessageType* = enum\n")
  s.add("    dmtDefault, dmtFallVariants, dmtIntentionalGameDesign\n\n")
  s.add("  DamageEffects* = enum\n")
  s.add("    deHurt, deThorns, deDrowning, deBurning, dePoking, deFreezing\n\n")
  s.add("  DamageScaling* = enum\n")
  s.add("    dsNever, dsWhenCausedByLivingNonPlayer, dsAlways\n\n")
  s.add("  DamageType* = object\n")
  s.add("    deathMessageType*: DeathMessageType\n")
  s.add("    exhaustion*: float32\n")
  s.add("    hasEffects*: bool\n")
  s.add("    effects*: DamageEffects\n")
  s.add("    messageId*: string\n")
  s.add("    scaling*: DamageScaling\n")
  s.add("    id*: uint8\n\n")

  proc deathMsgIdent(v: string): string =
    case v
    of "fall_variants": "dmtFallVariants"
    of "intentional_game_design": "dmtIntentionalGameDesign"
    else: "dmtDefault"

  proc effectsIdent(v: string): string =
    case v
    of "hurt": "deHurt"
    of "thorns": "deThorns"
    of "drowning": "deDrowning"
    of "burning": "deBurning"
    of "poking": "dePoking"
    of "freezing": "deFreezing"
    else: "deHurt"

  proc scalingIdent(v: string): string =
    case v
    of "never": "dsNever"
    of "always": "dsAlways"
    else: "dsWhenCausedByLivingNonPlayer"

  for i, e in entries:
    let cname = toShoutySnakeCase(e.name)
    s.add("const " & cname & "*: DamageType = DamageType(\n")
    s.add("  deathMessageType: " & deathMsgIdent(e.deathMessageType) & ",\n")
    s.add("  exhaustion: " & $e.exhaustion & "'f32,\n")
    s.add("  hasEffects: " & (if e.effects.len > 0: "true" else: "false") & ",\n")
    s.add("  effects: " & effectsIdent(e.effects) & ",\n")
    s.add("  messageId: \"" & e.messageId & "\",\n")
    s.add("  scaling: " & scalingIdent(e.scaling) & ",\n")
    s.add("  id: " & $i & "'u8)\n\n")

  s.add("proc damageTypeFromName*(name: string): (bool, DamageType) =\n")
  s.add("  case name\n")
  for e in entries:
    s.add("  of \"" & e.name & "\": (true, " & toShoutySnakeCase(e.name) & ")\n")
  s.add("  else: (false, " & toShoutySnakeCase(entries[0].name) & ")\n\n")

  s.add("proc damageTypeFromId*(id: uint8): (bool, DamageType) =\n")
  s.add("  case id\n")
  for i, e in entries:
    s.add("  of " & $i & "'u8: (true, " & toShoutySnakeCase(e.name) & ")\n")
  s.add("  else: (false, " & toShoutySnakeCase(entries[0].name) & ")\n")

  s

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
