## Port of tools/codegen/src/message_type.rs.
##
## Unlike the flat-JSON generators so far, this one reads a directory of
## `.json` files (one per chat-type entry, filename stem = the id) rather
## than a single JSON document, and emits `u8` constants numbered by sorted
## filename order plus a synthetic trailing `RAW` constant.
##
## Run with `nimony c -r src/data_codegen/gen_message_type.nim` from the
## repo root.

import std/[syncio, paths, dirs, algorithm, strutils]
import codegenutil

const OutPath = "src/generated/message_type.nim"

proc lastIndexOf(s: string, c: char): int =
  ## `rfind` isn't available; scan backward by hand.
  result = -1
  var i = s.len - 1
  while i >= 0:
    if s[i] == c:
      return i
    dec i

proc stemOf(p: Path): string =
  ## `splitFile` isn't available; strip directory and `.json` by hand.
  var base = $p
  let slashIdx = max(lastIndexOf(base, '/'), lastIndexOf(base, '\\'))
  if slashIdx >= 0:
    base = base[(slashIdx + 1) .. ^1]
  if base.endsWith(".json"):
    base = base[0 ..< (base.len - 5)]
  base

proc build(datapackPath: Path): string =
  var stems: seq[string] = @[]
  try:
    for kind, entryPath in walkDir(datapackPath):
      if kind == pcFile and ($entryPath).endsWith(".json"):
        stems.add(stemOf(entryPath))
  except ErrorCode as e:
    echo "walkDir failed: " & $e
  stems.sort(proc(a, b: string): int = cmp(a, b))

  var s = "## GENERATED by src/data_codegen/gen_message_type.nim - do not edit by hand.\n\n"
  for i, stem in stems:
    s.add("const " & toShoutySnakeCase(stem) & "*: uint8 = " & $i & "\n")
  s.add("const RAW*: uint8 = " & $stems.len & " ## one higher than the highest vanilla id\n")
  s

when isMainModule:
  let datapackPath = path("../upstream-ref/assets/datapack/data/minecraft/chat_type")
  try:
    let generated = build(datapackPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
