## Port of tools/codegen/src/chat_type.rs. Directory-of-JSON-files shape,
## but the field needed (`chat.translation_key`) is one level nested, so
## this doesn't use codegenutil.jsonStringField (top-level only).
##
## Run with `nimony c -r src/data_codegen/gen_chat_type.nim` from the
## repo root.

import std/[syncio, paths, json]
import codegenutil

const OutPath = "src/generated/chat_type.nim"

proc chatTranslationKeyOf(p: Path): string =
  var tree = parseFile($p)
  let obj = root(tree)
  result = ""
  for key, val in obj.pairs():
    if key == "chat":
      for k2, v2 in val.pairs():
        if k2 == "translation_key":
          result = v2.getStr()

proc build(dir: Path): string =
  let entries = listJsonStems(dir)
  var names: seq[string] = @[]
  var translationKeys: seq[string] = @[]
  for (stem, p) in entries:
    names.add(stem)
    translationKeys.add(chatTranslationKeyOf(p))

  var s = "## GENERATED by src/data_codegen/gen_chat_type.nim - do not edit by hand.\n\n"
  s.add("type\n  ChatType* = enum\n")
  for n in names:
    s.add("    ct" & toPascalCase(n) & "\n")
  s.add("\n")

  s.add("proc chatTypeFromName*(name: string): (bool, ChatType) =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, ct" & toPascalCase(n) & ")\n")
  s.add("  else: (false, ct" & toPascalCase(names[0]) & ")\n\n")

  s.add("proc id*(t: ChatType): uint32 =\n")
  s.add("  uint32(ord(t))\n\n")

  s.add("proc toName*(t: ChatType): string =\n")
  s.add("  case t\n")
  for n in names:
    s.add("  of ct" & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(t: ChatType): string =\n")
  s.add("  case t\n")
  for n in names:
    s.add("  of ct" & toPascalCase(n) & ": \"minecraft:" & n & "\"\n")
  s.add("\n")

  s.add("proc translationKey*(t: ChatType): string =\n")
  s.add("  case t\n")
  for i, n in names:
    s.add("  of ct" & toPascalCase(n) & ": \"" & translationKeys[i] & "\"\n")
  s.add("\n")

  s.add("const AllChatTypes*: array[" & $names.len & ", ChatType] = [\n")
  for n in names:
    s.add("  ct" & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/chat_type")
  try:
    let generated = build(dir)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
