## Port of tools/codegen/src/painting_variant.rs.
##
## Reads a directory of per-painting JSON files plus a separate "tag" file
## (`tags/painting_variant/placeable.json`) listing which variants are
## placeable in survival, sorted by filename stem (matching upstream's
## `BTreeMap<String, _>` insertion, which is really just sorted-by-stem
## since the loop inserts in already-sorted dir order and BTreeMap would
## keep it that way regardless).
##
## Run with `nimony c -r src/data_codegen/gen_painting_variant.nim` from
## the minecraft-server repo root.

import std/[syncio, json, paths]
import codegenutil

const OutPath = "src/generated/painting_variant.nim"

type
  PaintingEntry = object
    stem: string
    assetId: string
    width, height: int
    title: string   # "" means no title (Option<String>::None)
    author: string  # "" means no author
    placeable: bool

proc readPlaceableSet(tagPath: string): seq[string] =
  ## Port of `TagJson { values: Vec<String> }` - falls back to empty if
  ## the tag file doesn't exist (upstream's `tag_file.exists()` check).
  result = @[]
  try:
    var tree = parseFile(tagPath)
    let obj = root(tree)
    for k, val in obj.pairs():
      if k == "values":
        for v in val.items():
          result.add(v.getStr())
  except ErrorCode:
    discard

proc isPlaceable(placeableSet: seq[string], stem: string): bool =
  let namespaced = "minecraft:" & stem
  for v in placeableSet:
    if v == namespaced or v == stem:
      return true
  false

proc build(assetsPath: string): string =
  let dir = path(assetsPath & "/datapack/data/minecraft/painting_variant")
  let placeableSet = readPlaceableSet(
    assetsPath & "/datapack/data/minecraft/tags/painting_variant/placeable.json")

  var entries: seq[PaintingEntry] = @[]
  for (stem, path) in listJsonStems(dir):
    var e = PaintingEntry(stem: stem, assetId: "", width: 0, height: 0,
      title: "", author: "", placeable: isPlaceable(placeableSet, stem))
    e.assetId = jsonStringField(path, "asset_id")
    e.width = jsonIntField(path, "width", 0)
    e.height = jsonIntField(path, "height", 0)
    e.title = jsonNestedStringField(path, "title", "translate")
    e.author = jsonNestedStringField(path, "author", "translate")
    entries.add(e)

  var s = "## GENERATED by src/data_codegen/gen_painting_variant.nim - do not edit by hand.\n\n"
  s.add("type\n  PaintingVariant* = enum\n")
  for e in entries:
    s.add("    pv" & toPascalCase(e.stem) & "\n")
  s.add("\n")

  s.add("proc paintingVariantFromName*(name: string): (bool, PaintingVariant) =\n")
  s.add("  case name\n")
  for e in entries:
    s.add("  of \"" & e.assetId & "\", \"" & e.stem & "\": (true, pv" & toPascalCase(e.stem) & ")\n")
  s.add("  else: (false, pv" & toPascalCase(entries[0].stem) & ")\n\n")

  s.add("proc id*(v: PaintingVariant): uint32 = uint32(ord(v))\n\n")

  s.add("proc toName*(v: PaintingVariant): string =\n")
  s.add("  case v\n")
  for e in entries:
    s.add("  of pv" & toPascalCase(e.stem) & ": \"" & e.stem & "\"\n")
  s.add("\n")

  s.add("proc assetId*(v: PaintingVariant): string =\n")
  s.add("  case v\n")
  for e in entries:
    s.add("  of pv" & toPascalCase(e.stem) & ": \"" & e.assetId & "\"\n")
  s.add("\n")

  s.add("proc width*(v: PaintingVariant): uint32 =\n")
  s.add("  case v\n")
  for e in entries:
    s.add("  of pv" & toPascalCase(e.stem) & ": " & $e.width & "'u32\n")
  s.add("\n")

  s.add("proc height*(v: PaintingVariant): uint32 =\n")
  s.add("  case v\n")
  for e in entries:
    s.add("  of pv" & toPascalCase(e.stem) & ": " & $e.height & "'u32\n")
  s.add("\n")

  s.add("proc title*(v: PaintingVariant): string =\n")
  s.add("  case v\n")
  for e in entries:
    s.add("  of pv" & toPascalCase(e.stem) & ": \"" & e.title & "\"\n")
  s.add("\n")

  s.add("proc author*(v: PaintingVariant): (bool, string) =\n")
  s.add("  ## First value: whether an author translation key exists at all\n")
  s.add("  ## (mirrors upstream's `Option<&str>`).\n")
  s.add("  case v\n")
  for e in entries:
    if e.author.len > 0:
      s.add("  of pv" & toPascalCase(e.stem) & ": (true, \"" & e.author & "\")\n")
    else:
      s.add("  of pv" & toPascalCase(e.stem) & ": (false, \"\")\n")
  s.add("\n")

  s.add("proc isPlaceable*(v: PaintingVariant): bool =\n")
  s.add("  case v\n")
  for e in entries:
    s.add("  of pv" & toPascalCase(e.stem) & ": " & $e.placeable & "\n")
  s.add("\n")

  s.add("proc allPaintingVariants*(): seq[PaintingVariant] =\n")
  s.add("  @[\n")
  for e in entries:
    s.add("    pv" & toPascalCase(e.stem) & ",\n")
  s.add("  ]\n\n")

  s.add("proc allPlaceablePaintingVariants*(): seq[PaintingVariant] =\n")
  s.add("  @[\n")
  for e in entries:
    if e.placeable:
      s.add("    pv" & toPascalCase(e.stem) & ",\n")
  s.add("  ]\n")

  s

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
