## Generates src/generated/noise_parameter.nim from the real
## worldgen/noise JSON files, following the pattern established by
## gen_sound_category.nim. Port of upstream/tools/pumpkin-codegen/src/noise_parameter.rs
##
## Upstream's `collect_noise_files` recurses into subdirectories, but the
## real asset directory (checked: `assets/datapack/data/minecraft/worldgen/noise/`)
## has none (64 flat `.json` files, 0 subdirectories) - so this generator
## walks one level, not recursively. If a future asset update adds
## subdirectories, this needs revisiting (recursion itself is fine in
## Nimony; the two-pass split below is what's actually load-bearing, per
## the readFile-inside-walkDir-try bug noted in codegenutil.nim's history).

import std/[json, paths, dirs, syncio, md5, strutils]
import codegenutil

const NoiseDir = "../upstream-ref/assets/datapack/data/minecraft/worldgen/noise"

type
  NoiseParam = object
    firstOctave: int32
    amplitudes: seq[float64]

proc collectJsonPaths(dir: Path): seq[Path] =
  ## Two-pass split: this proc ONLY walks the directory (no readFile calls
  ## inside its try/walkDir scope), because nesting a readFile call inside
  ## a walkDir-iterating try block was found to produce broken C codegen
  ## elsewhere in this port (nimony check passes, runtime output is wrong) -
  ## see codegenutil.nim's/gen_context_provider.nim's notes.
  result = @[]
  try:
    for kind, p in walkDir(dir):
      if kind == pcFile and ($p).endsWith(".json"):
        result.add(p)
  except:
    discard

proc parseNoiseFile(p: Path): NoiseParam =
  var content: string
  try:
    content = readFile($p)
  except:
    content = "{}"
  var tree = parseJson(content)
  var firstOctave: int32 = -7
  let (hasFo, fo) = jsonTryGet(tree, "first_octave")
  let (hasBo, bo) = jsonTryGet(tree, "base_octave")
  if hasFo:
    firstOctave = int32(fo.getInt())
  elif hasBo:
    firstOctave = int32(bo.getInt())

  var amplitudes: seq[float64] = @[]
  let (hasAmp, amp) = jsonTryGet(tree, "amplitudes")
  let (hasAmpMod, ampMod) = jsonTryGet(tree, "amplitude_modifiers")
  let (hasOctCount, octCount) = jsonTryGet(tree, "octave_count")
  if hasAmp:
    for x in amp.items:
      amplitudes.add(x.getFloat())
  elif hasAmpMod:
    for x in ampMod.items:
      amplitudes.add(x.getFloat())
  elif hasOctCount:
    let n = octCount.getInt()
    let count = (if n < 1: 1 else: int(n))
    for i in 0 ..< count:
      amplitudes.add(1.0)
  else:
    amplitudes.add(1.0)

  result = NoiseParam(firstOctave: firstOctave, amplitudes: amplitudes)

proc insertionSortByKey(entries: var seq[(string, NoiseParam)]) =
  ## Manual insertion sort, not `.sort()` with a closure comparator -
  ## `seq[T].sort(closure)` is known to crash C-codegen when T is an
  ## object with an enum field; NoiseParam has none, but staying
  ## closure-free here is cheap and avoids re-litigating that bug class.
  for i in 1 ..< entries.len:
    var j = i
    while j > 0 and entries[j-1][0] > entries[j][0]:
      let tmp = entries[j-1]
      entries[j-1] = entries[j]
      entries[j] = tmp
      dec j

proc main() =
  let paths = collectJsonPaths(path(NoiseDir))
  var entries: seq[(string, NoiseParam)] = @[]
  for p in paths:
    let name = stemOf(p)
    entries.add((name, parseNoiseFile(p)))
  insertionSortByKey(entries)

  var s = "## Generated by gen_noise_parameter.nim. DO NOT EDIT BY HAND.\n"
  s.add("## Port of upstream/tools/pumpkin-codegen/src/noise_parameter.rs's\n")
  s.add("## DoublePerlinNoiseParameters table, from the real worldgen/noise assets.\n\n")
  s.add("type\n")
  s.add("  DoublePerlinNoiseParameters* = object\n")
  s.add("    id*: int\n")
  s.add("    firstOctave*: int32\n")
  s.add("    amplitudes*: seq[float64]\n")
  s.add("    lo*: uint64\n")
  s.add("    hi*: uint64\n\n")

  s.add("proc allNoiseParameters*(): seq[DoublePerlinNoiseParameters] =\n")
  s.add("  ## seq[T] literal, built by a proc rather than a `const` - a\n")
  s.add("  ## `const seq[T]` referencing computed values isn't always\n")
  s.add("  ## foldable at Nimony compile time (seen elsewhere in this port).\n")
  s.add("  result = @[]\n")
  for i, (name, param) in entries:
    let fullName = "minecraft:" & name
    let digest = toMD5(fullName)
    var lo: uint64 = 0
    for k in 0 ..< 8:
      lo = (lo shl 8) or uint64(digest[k])
    var hi: uint64 = 0
    for k in 8 ..< 16:
      hi = (hi shl 8) or uint64(digest[k])
    var amps = "@["
    for j, a in param.amplitudes:
      if j > 0: amps.add(", ")
      amps.add($a)
    amps.add("]")
    s.add("  result.add(DoublePerlinNoiseParameters(id: " & $i &
      ", firstOctave: " & $param.firstOctave &
      "'i32, amplitudes: " & amps &
      ", lo: " & $lo & "'u64, hi: " & $hi & "'u64)) # " & fullName & "\n")

  s.add("\nproc idToParameters*(id: string): (bool, DoublePerlinNoiseParameters) =\n")
  s.add("  var key = id\n")
  s.add("  if key.len > 10 and key[0 ..< 10] == \"minecraft:\":\n")
  s.add("    key = key[10 ..< key.len]\n")
  s.add("  let all = allNoiseParameters()\n")
  s.add("  let names = [")
  for i, (name, _) in entries:
    if i > 0: s.add(", ")
    s.add("\"" & name & "\"")
  s.add("]\n")
  s.add("  for i in 0 ..< names.len:\n")
  s.add("    if names[i] == key:\n")
  s.add("      return (true, all[i])\n")
  s.add("  (false, DoublePerlinNoiseParameters())\n")

  try:
    writeFile("src/generated/noise_parameter.nim", s)
  except:
    echo "FAILED to write output file"
  echo "wrote src/generated/noise_parameter.nim with ", entries.len, " noise parameter entries"

main()
