## Port of tools/codegen/src/decorated_pot_pattern.rs.
## Directory of one-field JSON files (name = filename stem, value =
## {"asset_id": "minecraft:<name>_pottery_pattern"}), same directory-walk
## shape as gen_message_type.nim. Final order is alphabetical by stem
## (upstream collects into a BTreeMap keyed by stem).
##
## Run with `nimony c -r src/data_codegen/gen_decorated_pot_pattern.nim`
## from the repo root.

import std/[syncio, paths, dirs, algorithm, json, strutils]
import codegenutil

const OutPath = "src/generated/decorated_pot_pattern.nim"

proc lastIndexOf(s: string, c: char): int =
  result = -1
  var i = s.len - 1
  while i >= 0:
    if s[i] == c:
      return i
    dec i

proc stemOf(p: Path): string =
  var base = $p
  let slashIdx = max(lastIndexOf(base, '/'), lastIndexOf(base, '\\'))
  if slashIdx >= 0:
    base = base[(slashIdx + 1) .. ^1]
  if base.endsWith(".json"):
    base = base[0 ..< (base.len - 5)]
  base

proc assetIdOf(p: Path): string =
  var tree = parseFile($p)
  let obj = root(tree)
  result = ""
  for key, val in obj.pairs():
    if key == "asset_id":
      result = val.getStr()

proc build(datapackPath: Path): string =
  var names: seq[string] = @[]
  var assetIds: seq[string] = @[]
  try:
    var fullPaths: seq[Path] = @[]
    for kind, entryPath in walkDir(datapackPath):
      if kind == pcFile and ($entryPath).endsWith(".json"):
        fullPaths.add(entryPath)
    fullPaths.sort(proc(a, b: Path): int = cmp($a, $b))
    for p in fullPaths:
      names.add(stemOf(p))
      assetIds.add(assetIdOf(p))
  except ErrorCode as e:
    echo "walkDir/parse failed: " & $e

  var s = "## GENERATED by src/data_codegen/gen_decorated_pot_pattern.nim - do not edit by hand.\n\n"
  s.add("type\n  DecoratedPotPattern* = enum\n")
  for n in names:
    s.add("    dpp" & toPascalCase(n) & "\n")
  s.add("\n")

  s.add("proc decoratedPotPatternFromName*(name: string): (bool, DecoratedPotPattern) =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, dpp" & toPascalCase(n) & ")\n")
  s.add("  else: (false, dpp" & toPascalCase(names[0]) & ")\n\n")

  s.add("proc id*(p: DecoratedPotPattern): uint32 =\n")
  s.add("  uint32(ord(p))\n\n")

  s.add("proc toName*(p: DecoratedPotPattern): string =\n")
  s.add("  case p\n")
  for n in names:
    s.add("  of dpp" & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(p: DecoratedPotPattern): string =\n")
  s.add("  case p\n")
  for i, n in names:
    s.add("  of dpp" & toPascalCase(n) & ": \"" & assetIds[i] & "\"\n")
  s.add("\n")

  s.add("const AllDecoratedPotPatterns*: array[" & $names.len & ", DecoratedPotPattern] = [\n")
  for n in names:
    s.add("  dpp" & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  let datapackPath = path("../upstream-ref/assets/datapack/data/minecraft/decorated_pot_pattern")
  try:
    let generated = build(datapackPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
