## Port of tools/pumpkin-codegen/src/item.rs, SCOPED per directive: only the
## name/id/max-stack-size table, not the full per-item `components` map
## (data_component.rs's ~2887-line registry/codec is a separate, much larger
## unported prerequisite - see src/protocol/README.md's item_stack_seralizer.rs
## note). `assets/items.json` is a JSON *object* keyed by item name (not an
## array), value `{id, components: {...}}` - we read `id` and
## `components["minecraft:max_stack_size"]` (default 64 when absent, matching
## upstream's `#[serde(default = "default_stack_size")]`) and ignore
## everything else in `components`.

import std/[json, syncio, algorithm]
import codegenutil

type
  ItemEntry = object
    id: int
    name: string
    maxStackSize: int

proc readItems(path: string): seq[ItemEntry] =
  var tree = parseFile(path)
  let obj = root(tree)
  result = @[]
  for name, val in obj.pairs():
    var entry = ItemEntry(id: 0, name: name, maxStackSize: 64)
    for k, v in val.pairs():
      case k
      of "id": entry.id = int(v.getInt())
      of "components":
        for ck, cv in v.pairs():
          if ck == "minecraft:max_stack_size":
            entry.maxStackSize = int(cv.getInt())
      else: discard
    result.add(entry)
  result.sort(proc(a, b: ItemEntry): int = cmp(a.id, b.id))

proc main() =
  let items = readItems("../upstream-ref/assets/items.json")
  var s = "## Generated by src/data_codegen/gen_item.nim from assets/items.json.\n"
  s.add("## SCOPED: name/id/maxStackSize only - see gen_item.nim's doc comment\n")
  s.add("## for why the full `components` map isn't ported here.\n\n")
  s.add("type\n  Item* = object\n    id*: int\n    name*: string\n    maxStackSize*: int\n\n")
  s.add("let AllItems*: seq[Item] = @[\n")
  for it in items:
    s.add("  Item(id: " & $it.id & ", name: \"" & it.name & "\", maxStackSize: " &
          $it.maxStackSize & "),\n")
  s.add("]\n\n")
  s.add("proc itemById*(id: int): (bool, Item) =\n")
  s.add("  for it in AllItems:\n    if it.id == id: return (true, it)\n")
  s.add("  (false, Item())\n\n")
  s.add("proc itemByName*(name: string): (bool, Item) =\n")
  s.add("  for it in AllItems:\n    if it.name == name: return (true, it)\n")
  s.add("  (false, Item())\n")
  try:
    writeFile("../minecraft-server/src/generated/item.nim", s)
  except ErrorCode as e:
    echo "writeFile failed: " & $e
  echo "wrote " & $items.len & " items"

main()
