## Port of tools/codegen/src/chunk_status.rs.
##
## Reads `assets/chunk_status.json` (a flat string array) and emits a
## `ChunkStatus` enum, plus name<->value helpers (standing in for the
## upstream `#[serde(rename = "minecraft:<status>")]` attributes, since
## there's no serde-equivalent (de)serialization layer wired up yet - the
## `minecraft:<name>` wire string is still recoverable via `chunkStatusToWireName`).
##
## Run with `nimony c -r src/data_codegen/gen_chunk_status.nim` from the
## repo root.

import std/[syncio, strutils]
import codegenutil

const OutPath = "src/generated/chunk_status.nim"

proc build(assetsPath: string): string =
  let statuses = readStringArray(assetsPath & "/chunk_status.json")

  var s = "## GENERATED by src/data_codegen/gen_chunk_status.nim - do not edit by hand.\n\n"
  s.add("type\n  ChunkStatus* = enum\n")
  for st in statuses:
    s.add("    cs" & toPascalCase(st) & "\n")
  s.add("\n")

  s.add("proc chunkStatusFromName*(name: string): (bool, ChunkStatus) =\n")
  s.add("  case name\n")
  for st in statuses:
    s.add("  of \"" & st & "\": (true, cs" & toPascalCase(st) & ")\n")
  s.add("  else: (false, cs" & toPascalCase(statuses[0]) & ")\n\n")

  s.add("proc chunkStatusToName*(c: ChunkStatus): string =\n")
  s.add("  case c\n")
  for st in statuses:
    s.add("  of cs" & toPascalCase(st) & ": \"" & st & "\"\n")
  s.add("\n")

  s.add("proc chunkStatusToWireName*(c: ChunkStatus): string =\n")
  s.add("  ## The upstream `#[serde(rename = \"minecraft:<status>\")]` wire form.\n")
  s.add("  \"minecraft:\" & chunkStatusToName(c)\n")

  s

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
