## Port of tools/codegen/src/banner_pattern.rs. Directory-of-JSON-files
## shape (see codegenutil.listJsonStems), two string fields per entry.
##
## Run with `nimony c -r src/data_codegen/gen_banner_pattern.nim` from the
## repo root.

import std/[syncio, paths]
import codegenutil

const OutPath = "src/generated/banner_pattern.nim"

proc build(dir: Path): string =
  let entries = listJsonStems(dir)
  var names: seq[string] = @[]
  var assetIds: seq[string] = @[]
  var translationKeys: seq[string] = @[]
  for (stem, p) in entries:
    names.add(stem)
    assetIds.add(jsonStringField(p, "asset_id"))
    translationKeys.add(jsonStringField(p, "translation_key"))

  var s = "## GENERATED by src/data_codegen/gen_banner_pattern.nim - do not edit by hand.\n\n"
  s.add("type\n  BannerPattern* = enum\n")
  for n in names:
    s.add("    bp" & toPascalCase(n) & "\n")
  s.add("\n")

  s.add("proc bannerPatternFromName*(name: string): (bool, BannerPattern) =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, bp" & toPascalCase(n) & ")\n")
  s.add("  else: (false, bp" & toPascalCase(names[0]) & ")\n\n")

  s.add("proc id*(p: BannerPattern): uint32 =\n")
  s.add("  uint32(ord(p))\n\n")

  s.add("proc toName*(p: BannerPattern): string =\n")
  s.add("  case p\n")
  for n in names:
    s.add("  of bp" & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(p: BannerPattern): string =\n")
  s.add("  case p\n")
  for i, n in names:
    s.add("  of bp" & toPascalCase(n) & ": \"" & assetIds[i] & "\"\n")
  s.add("\n")

  s.add("proc translationKey*(p: BannerPattern): string =\n")
  s.add("  case p\n")
  for i, n in names:
    s.add("  of bp" & toPascalCase(n) & ": \"" & translationKeys[i] & "\"\n")
  s.add("\n")

  s.add("const AllBannerPatterns*: array[" & $names.len & ", BannerPattern] = [\n")
  for n in names:
    s.add("  bp" & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/banner_pattern")
  try:
    let generated = build(dir)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
