## Port of tools/codegen/src/trim_pattern.rs. Directory-of-JSON-files shape,
## with `asset_id` and `decal` (bool, default false) top-level fields and a
## nested `description.translate` (Option<String>, defaulting to "").
##
## Run with `nimony c -r src/data_codegen/gen_trim_pattern.nim` from the
## repo root.

import std/[syncio, paths]
import codegenutil

const OutPath = "src/generated/trim_pattern.nim"

proc build(dir: Path): string =
  let entries = listJsonStems(dir)
  var names: seq[string] = @[]
  var assetIds, translationKeys: seq[string] = @[]
  var decals: seq[bool] = @[]
  for (stem, p) in entries:
    names.add(stem)
    assetIds.add(jsonStringField(p, "asset_id"))
    decals.add(jsonBoolField(p, "decal", false))
    translationKeys.add(jsonNestedStringField(p, "description", "translate"))

  var s = "## GENERATED by src/data_codegen/gen_trim_pattern.nim - do not edit by hand.\n\n"
  s.add("type\n  TrimPattern* = enum\n")
  for n in names:
    s.add("    tp" & toPascalCase(n) & "\n")
  s.add("\n")

  s.add("proc trimPatternFromName*(name: string): (bool, TrimPattern) =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, tp" & toPascalCase(n) & ")\n")
  s.add("  else: (false, tp" & toPascalCase(names[0]) & ")\n\n")

  s.add("proc id*(v: TrimPattern): uint32 =\n")
  s.add("  uint32(ord(v))\n\n")

  s.add("proc toName*(v: TrimPattern): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of tp" & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(v: TrimPattern): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of tp" & toPascalCase(n) & ": \"" & assetIds[i] & "\"\n")
  s.add("\n")

  s.add("proc isDecal*(v: TrimPattern): bool =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of tp" & toPascalCase(n) & ": " & (if decals[i]: "true" else: "false") & "\n")
  s.add("\n")

  s.add("proc translationKey*(v: TrimPattern): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of tp" & toPascalCase(n) & ": \"" & translationKeys[i] & "\"\n")
  s.add("\n")

  s.add("const AllTrimPatterns*: array[" & $names.len & ", TrimPattern] = [\n")
  for n in names:
    s.add("  tp" & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/trim_pattern")
  try:
    let generated = build(dir)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
