## Port of tools/pumpkin-codegen/src/bedrock_creative.rs, JSON-input
## branch only (the `.json` branch is the one whose assets actually
## exist under `assets/bedrock/`; the `.nbt`-file and
## previously-generated-file fallback branches upstream falls back to
## when the JSON is absent don't apply here and aren't ported).
##
## Reads `bedrock/runtime_item_states.json` (a flat name->id array) to
## build a name->id lookup, then `bedrock/creative_items.json` (groups +
## items, each referencing an item by Java-style `minecraft:name` id) to
## emit `CREATIVE_GROUPS`/`CREATIVE_ENTRIES`. `category` string->int
## mapping matches upstream's exactly (construction=1, nature=2,
## equipment=3, items=4, itemCommandOnly=5, else=6). Entries whose item
## id has no match in the runtime-item-states table are silently
## dropped, matching upstream's `filter_map`/`?`.
##
## The `block_state_b64` field on each group's icon is read by upstream
## only to eventually feed the (unused-here) icon block-state lookup -
## this port only needs `icon.id`, so that field is ignored.

import std/[json, paths, strutils, syncio]
import codegenutil

type
  CreativeGroup* = object
    category*: int
    name*: string
    iconItemId*: int16
    iconItemAuxValue*: uint32

  CreativeEntry* = object
    itemId*: int16
    itemAuxValue*: uint32
    groupIndex*: uint32

proc safeGet(n: JsonNode, key: string): (bool, JsonNode) =
  ## Node-level equivalent of `codegenutil.jsonTryGet` (which only
  ## operates on a `var JsonTree`'s root) - this generator needs safe
  ## lookup on nested object nodes several levels deep. Scans `pairs`
  ## itself rather than using `{}`, which returns a default-constructed
  ## `JsonNode()` on a missing key and crashes at RUNTIME (not
  ## `nimony check`) on almost any use of that default - see
  ## `jsonTryGet`'s doc comment / NIMONY-COMPILER-BUGS.md for the full
  ## writeup of that trap.
  if kind(n) != JObject:
    return (false, n)
  for k, v in pairs(n):
    if k == key:
      return (true, v)
  (false, n)

proc safeGetStr(n: JsonNode, key, default: string): string =
  let (found, v) = safeGet(n, key)
  if found: getStr(v, default) else: default

proc safeGetInt(n: JsonNode, key: string, default: int64): int64 =
  let (found, v) = safeGet(n, key)
  if found: getInt(v, default) else: default

proc categoryOf(s: string): int =
  case s
  of "construction": 1
  of "nature": 2
  of "equipment": 3
  of "items": 4
  of "itemCommandOnly": 5
  else: 6

proc loadRuntimeItemStates(path: string): seq[(string, int16)] =
  ## Flat array of {name, id, version, componentBased} objects.
  var tree = parseFile(path)
  result = @[]
  for entry in items(root(tree)):
    let name = safeGetStr(entry, "name", "")
    if name.len == 0:
      continue
    let id = int16(safeGetInt(entry, "id", 0))
    result.add((name, id))

proc lookupId(states: seq[(string, int16)], name: string): (bool, int16) =
  for (n, id) in states:
    if n == name:
      return (true, id)
  (false, 0'i16)

proc generateBedrockCreative*(assetsDir, outPath: string) =
  let states = loadRuntimeItemStates(assetsDir & "/bedrock/runtime_item_states.json")

  var creativeTree = parseFile(assetsDir & "/bedrock/creative_items.json")
  let creativeRoot = root(creativeTree)

  var groups: seq[CreativeGroup] = @[]
  let (foundGroups, groupsNode) = safeGet(creativeRoot, "groups")
  discard foundGroups
  for g in items(groupsNode):
    let category = categoryOf(safeGetStr(g, "category", ""))
    let name = safeGetStr(g, "name", "")
    let (foundIconNode, iconNode) = safeGet(g, "icon")
    discard foundIconNode
    let iconId = safeGetStr(iconNode, "id", "")
    let (foundIcon, iconItemId) = lookupId(states, iconId)
    groups.add(CreativeGroup(
      category: category,
      name: name,
      iconItemId: (if foundIcon: iconItemId else: 0'i16),
      iconItemAuxValue: 0'u32,
    ))

  var entries: seq[CreativeEntry] = @[]
  let (foundItems, itemsNode) = safeGet(creativeRoot, "items")
  discard foundItems
  for it in items(itemsNode):
    let itemId = safeGetStr(it, "id", "")
    let (foundItem, resolvedId) = lookupId(states, itemId)
    if not foundItem:
      continue
    let damage = uint32(safeGetInt(it, "damage", 0))
    let groupId = uint32(safeGetInt(it, "groupId", 0))
    entries.add(CreativeEntry(
      itemId: resolvedId,
      itemAuxValue: damage,
      groupIndex: groupId,
    ))

  var src = "## Generated by src/data_codegen/gen_bedrock_creative.nim from " &
    "upstream/tools/pumpkin-codegen/src/bedrock_creative.rs + " &
    "assets/bedrock/{runtime_item_states,creative_items}.json\n" &
    "## Do not edit by hand.\n\n" &
    "type\n" &
    "  CreativeGroup* = object\n" &
    "    category*: int\n" &
    "    name*: string\n" &
    "    iconItemId*: int16\n" &
    "    iconItemAuxValue*: uint32\n\n" &
    "  CreativeEntry* = object\n" &
    "    itemId*: int16\n" &
    "    itemAuxValue*: uint32\n" &
    "    groupIndex*: uint32\n\n" &
    "proc creativeGroups*(): seq[CreativeGroup] =\n" &
    "  result = @[]\n"
  for g in groups:
    src.add("  result.add(CreativeGroup(category: " & $g.category &
      ", name: \"" & g.name & "\", iconItemId: " & $g.iconItemId &
      "'i16, iconItemAuxValue: " & $g.iconItemAuxValue & "'u32))\n")
  src.add("\nproc creativeEntries*(): seq[CreativeEntry] =\n  result = @[]\n")
  for e in entries:
    src.add("  result.add(CreativeEntry(itemId: " & $e.itemId &
      "'i16, itemAuxValue: " & $e.itemAuxValue & "'u32, groupIndex: " &
      $e.groupIndex & "'u32))\n")

  try:
    writeFile(outPath, src)
  except ErrorCode as e:
    echo "generateBedrockCreative: writeFile failed: " & $e

when isMainModule:
  generateBedrockCreative("../upstream-ref/assets", "src/generated/bedrock_creative.nim")
