## Generator for `StatisticCategory` and `CustomStatistic`.
## Port of upstream/tools/codegen/src/statistic.rs

import std/[json, syncio]
import codegenutil

proc stripMc(s: string): string =
  if s.len > 10 and s[0..9] == "minecraft:": s[10..^1]
  else: s

proc main() =
  var tree = parseFile("../upstream-ref/assets/stats.json")
  let statsRoot = root(tree)

  var categoryVariants = ""
  var categoryFromIdArms = ""
  var categoryFromNameArms = ""
  var customVariants = ""
  var customFromIdArms = ""

  for categoryName, data in statsRoot.pairs():
    let categoryIdent = toPascalCase(stripMc(categoryName))
    var categoryId = 0
    var entries: seq[(string, int)] = @[]
    for key, val in data.pairs():
      case key
      of "id": categoryId = int(val.getInt())
      of "entries":
        for statName, entry in val.pairs():
          for ekey, eval in entry.pairs():
            if ekey == "id":
              entries.add((statName, int(eval.getInt())))
      else: discard

    categoryVariants.add("    sc" & categoryIdent & " = " & $categoryId & "\n")
    categoryFromIdArms.add("  of " & $categoryId & ": (true, sc" & categoryIdent & ")\n")
    categoryFromNameArms.add("  of \"" & stripMc(categoryName) & "\": (true, sc" & categoryIdent & ")\n")

    if categoryName == "minecraft:custom":
      for (statName, statId) in entries:
        let statIdent = toPascalCase(stripMc(statName))
        customVariants.add("    cs" & statIdent & " = " & $statId & "\n")
        customFromIdArms.add("  of " & $statId & ": (true, cs" & statIdent & ")\n")

  let output = "## The `StatisticCategory`/`CustomStatistic` registries.\n" &
    "## Generated by gen_statistic.nim from upstream/assets/stats.json - do not edit by hand.\n\n" &
    "type\n" &
    "  StatisticCategory* = enum\n" & categoryVariants & "\n" &
    "  CustomStatistic* = enum\n" & customVariants & "\n" &
    "proc categoryFromId*(id: int): (bool, StatisticCategory) =\n" &
    "  case id\n" & categoryFromIdArms & "  else: (false, StatisticCategory(0))\n\n" &
    "proc categoryFromRegistryKey*(name: string): (bool, StatisticCategory) =\n" &
    "  case name\n" & categoryFromNameArms & "  else: (false, StatisticCategory(0))\n\n" &
    "proc customStatFromId*(id: int): (bool, CustomStatistic) =\n" &
    "  case id\n" & customFromIdArms & "  else: (false, CustomStatistic(0))\n"

  try:
    writeFile("src/generated/statistic.nim", output)
  except ErrorCode as e:
    echo "write failed: " & $e
  echo "wrote src/generated/statistic.nim"

main()
