## Port of tools/codegen/src/cat_variant.rs. Directory-of-JSON-files shape
## (see codegenutil.listJsonStems). Note upstream's own naming quirk,
## preserved here: `asset_id()` returns the *namespaced resource name*
## (`minecraft:<stem>`), while `texture()` returns the JSON file's
## `asset_id` field (the actual texture path) - those are two different
## strings despite the confusing method name.
##
## Run with `nimony c -r src/data_codegen/gen_cat_variant.nim` from the
## repo root.

import std/[syncio, paths]
import codegenutil

const OutPath = "src/generated/cat_variant.nim"

proc build(dir: Path): string =
  let entries = listJsonStems(dir)
  var names: seq[string] = @[]
  var textures: seq[string] = @[]
  for (stem, p) in entries:
    names.add(stem)
    textures.add(jsonStringField(p, "asset_id"))

  var s = "## GENERATED by src/data_codegen/gen_cat_variant.nim - do not edit by hand.\n\n"
  s.add("type\n  CatVariant* = enum\n")
  for n in names:
    s.add("    cv" & toPascalCase(n) & "\n")
  s.add("\n")

  s.add("proc catVariantFromName*(name: string): (bool, CatVariant) =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, cv" & toPascalCase(n) & ")\n")
  s.add("  else: (false, cv" & toPascalCase(names[0]) & ")\n\n")

  s.add("proc id*(v: CatVariant): uint8 =\n")
  s.add("  uint8(ord(v))\n\n")

  s.add("proc toName*(v: CatVariant): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of cv" & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(v: CatVariant): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of cv" & toPascalCase(n) & ": \"minecraft:" & n & "\"\n")
  s.add("\n")

  s.add("proc texture*(v: CatVariant): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of cv" & toPascalCase(n) & ": \"" & textures[i] & "\"\n")
  s.add("\n")

  s.add("const AllCatVariants*: array[" & $names.len & ", CatVariant] = [\n")
  for n in names:
    s.add("  cv" & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/cat_variant")
  try:
    let generated = build(dir)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
