## Port of tools/codegen/src/wolf_variant.rs. Directory-of-JSON-files shape
## (see codegenutil.listJsonStems), with a nested `assets.{angry,tame,wild}`
## object per entry. `baby_assets`/`spawn_conditions` are read upstream but
## never actually used in the emitted TokenStream (dead fields in the
## deserialize struct) - skipped here too, faithfully matching upstream's
## real output rather than its struct shape.
##
## Run with `nimony c -r src/data_codegen/gen_wolf_variant.nim` from the
## repo root.

import std/[syncio, paths]
import codegenutil

const OutPath = "src/generated/wolf_variant.nim"

proc build(dir: Path): string =
  let entries = listJsonStems(dir)
  var names: seq[string] = @[]
  var wilds, tames, angries: seq[string] = @[]
  for (stem, p) in entries:
    names.add(stem)
    wilds.add(jsonNestedStringField(p, "assets", "wild"))
    tames.add(jsonNestedStringField(p, "assets", "tame"))
    angries.add(jsonNestedStringField(p, "assets", "angry"))

  var s = "## GENERATED by src/data_codegen/gen_wolf_variant.nim - do not edit by hand.\n\n"
  s.add("type\n  WolfVariant* = enum\n")
  for n in names:
    s.add("    wv" & toPascalCase(n) & "\n")
  s.add("\n")

  s.add("proc wolfVariantFromName*(name: string): (bool, WolfVariant) =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, wv" & toPascalCase(n) & ")\n")
  s.add("  else: (false, wv" & toPascalCase(names[0]) & ")\n\n")

  s.add("proc id*(v: WolfVariant): uint8 =\n")
  s.add("  uint8(ord(v))\n\n")

  s.add("proc toName*(v: WolfVariant): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of wv" & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(v: WolfVariant): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of wv" & toPascalCase(n) & ": \"minecraft:" & n & "\"\n")
  s.add("\n")

  s.add("proc wildTexture*(v: WolfVariant): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of wv" & toPascalCase(n) & ": \"" & wilds[i] & "\"\n")
  s.add("\n")

  s.add("proc tameTexture*(v: WolfVariant): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of wv" & toPascalCase(n) & ": \"" & tames[i] & "\"\n")
  s.add("\n")

  s.add("proc angryTexture*(v: WolfVariant): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of wv" & toPascalCase(n) & ": \"" & angries[i] & "\"\n")
  s.add("\n")

  s.add("const AllWolfVariants*: array[" & $names.len & ", WolfVariant] = [\n")
  for n in names:
    s.add("  wv" & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/wolf_variant")
  try:
    let generated = build(dir)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
