## Port of tools/codegen/src/mob_variant.rs's `build_entity_variant`, applied
## to its four callers (`build_cow`/`build_pig`/`build_chicken`/
## `build_zombie_nautilus`). Directory-of-JSON-files shape (see
## codegenutil.listJsonStems), one enum per animal kind.
##
## Scoped down from upstream, same "name/id table first" precedent as
## block.rs/item.rs: ported are the enum, asset_id/baby_asset_id/model
## tables, and fromName/toName/id. NOT ported: `spawn_conditions` and the
## `select_for_biome` biome-selection logic (temperate/cold/warm farm-animal
## variants, coral/warm zombie-nautilus variants) - upstream hardcodes that
## against `crate::tag::WorldgenBiome::MINECRAFT_SPAWNS_..._FARM_ANIMALS`
## biome-tag membership sets, which aren't generated anywhere in this port
## yet (no `tag.rs` generator has been ported). A future pass that ports
## `tag.rs` can add `selectForBiome` procs here using the same shape as
## `src/data_codegen/gen_wolf_variant.nim`'s output.
##
## Run with `nimony c -r src/data_codegen/gen_mob_variant.nim` from the
## repo root.

import std/[syncio, paths]
import codegenutil

type MobVariantSpec = object
  dirName: string
  enumName: string
  prefix: string
  outPath: string

const Specs = [
  MobVariantSpec(dirName: "cow_variant", enumName: "CowVariant", prefix: "cv", outPath: "src/generated/cow_variant.nim"),
  MobVariantSpec(dirName: "pig_variant", enumName: "PigVariant", prefix: "pv", outPath: "src/generated/pig_variant.nim"),
  MobVariantSpec(dirName: "chicken_variant", enumName: "ChickenVariant", prefix: "chv", outPath: "src/generated/chicken_variant.nim"),
  MobVariantSpec(dirName: "zombie_nautilus_variant", enumName: "ZombieNautilusVariant", prefix: "znv", outPath: "src/generated/zombie_nautilus_variant.nim"),
]

proc build(dir: Path, spec: MobVariantSpec): string =
  let entries = listJsonStems(dir)
  var names: seq[string] = @[]
  var assetIds, babyAssetIds, models: seq[string] = @[]
  for (stem, p) in entries:
    names.add(stem)
    assetIds.add(jsonStringField(p, "asset_id"))
    babyAssetIds.add(jsonStringField(p, "baby_asset_id"))
    models.add(jsonStringField(p, "model"))

  var s = "## GENERATED by src/data_codegen/gen_mob_variant.nim - do not edit by hand.\n\n"
  s.add("type\n  " & spec.enumName & "* = enum\n")
  for n in names:
    s.add("    " & spec.prefix & toPascalCase(n) & "\n")
  s.add("\n")

  s.add("proc " & spec.prefix & "FromName*(name: string): (bool, " & spec.enumName & ") =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, " & spec.prefix & toPascalCase(n) & ")\n")
  s.add("  else: (false, " & spec.prefix & toPascalCase(names[0]) & ")\n\n")

  s.add("proc id*(v: " & spec.enumName & "): uint8 =\n")
  s.add("  uint8(ord(v))\n\n")

  s.add("proc toName*(v: " & spec.enumName & "): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of " & spec.prefix & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(v: " & spec.enumName & "): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of " & spec.prefix & toPascalCase(n) & ": \"" & assetIds[i] & "\"\n")
  s.add("\n")

  s.add("proc babyAssetId*(v: " & spec.enumName & "): string =\n")
  s.add("  ## \"\" means upstream's `None` (no baby-specific texture).\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of " & spec.prefix & toPascalCase(n) & ": \"" & babyAssetIds[i] & "\"\n")
  s.add("\n")

  s.add("proc model*(v: " & spec.enumName & "): string =\n")
  s.add("  ## \"\" means upstream's `None` (default model).\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of " & spec.prefix & toPascalCase(n) & ": \"" & models[i] & "\"\n")
  s.add("\n")

  s.add("const All" & spec.enumName & "s*: array[" & $names.len & ", " & spec.enumName & "] = [\n")
  for n in names:
    s.add("  " & spec.prefix & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  for spec in Specs:
    let dir = path("../upstream-ref/assets/datapack/data/minecraft/" & spec.dirName)
    try:
      let generated = build(dir, spec)
      writeFile(spec.outPath, generated)
      echo "wrote " & spec.outPath & " (" & $generated.len & " bytes)"
    except ErrorCode as e:
      echo "generation failed for " & spec.dirName & ": " & $e
