## Port of tools/codegen/src/frog_variant.rs.
##
## Quirk worth flagging: upstream's `build()` scans the frog_variant/
## directory dynamically (like cat_variant/banner_pattern) to build
## `from_name`/`to_name`/`asset_id`/`texture`, but the `enum FrogVariant`
## itself is HARDCODED to exactly `Cold, Temperate (default), Warm` rather
## than generated from that scan - the scan's `enum_variants` list is built
## but never used. This only works because the directory happens to
## contain exactly `cold.json`/`temperate.json`/`warm.json` (verified).
## `from_id` is also hand-written with `Temperate` as the fallback for any
## unrecognized id, not `None`, unlike every other generator's `fromName`.
## Preserved faithfully here rather than "fixed" to be fully dynamic.
##
## Run with `nimony c -r src/data_codegen/gen_frog_variant.nim` from the
## repo root.

import std/[syncio, paths]
import codegenutil

const OutPath = "src/generated/frog_variant.nim"

proc build(dir: Path): string =
  let entries = listJsonStems(dir)
  var names: seq[string] = @[]
  var textures: seq[string] = @[]
  for (stem, p) in entries:
    names.add(stem)
    textures.add(jsonStringField(p, "asset_id"))

  var s = "## GENERATED by src/data_codegen/gen_frog_variant.nim - do not edit by hand.\n\n"
  s.add("type\n  FrogVariant* = enum\n    fvCold\n    fvTemperate\n    fvWarm\n\n")

  s.add("proc frogVariantFromName*(name: string): (bool, FrogVariant) =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, fv" & toPascalCase(n) & ")\n")
  s.add("  else: (false, fvTemperate)\n\n")

  s.add("proc id*(v: FrogVariant): uint32 =\n")
  s.add("  uint32(ord(v))\n\n")

  s.add("proc frogVariantFromId*(id: uint32): FrogVariant =\n")
  s.add("  case id\n  of 0'u32: fvCold\n  of 2'u32: fvWarm\n  else: fvTemperate\n\n")

  s.add("proc toName*(v: FrogVariant): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of fv" & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(v: FrogVariant): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of fv" & toPascalCase(n) & ": \"minecraft:" & n & "\"\n")
  s.add("\n")

  s.add("proc texture*(v: FrogVariant): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of fv" & toPascalCase(n) & ": \"" & textures[i] & "\"\n")
  s.add("\n")

  s.add("const AllFrogVariants*: array[" & $names.len & ", FrogVariant] = [\n")
  for n in names:
    s.add("  fv" & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/frog_variant")
  try:
    let generated = build(dir)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
