## Port of tools/codegen/src/flower_pot_transformations.rs.
##
## Reads `assets/flower_pot_transformations.json` (a `{item_id: potted_block_id}`
## map, both uint16 wire ids) and emits `getPottedItem(itemId): uint16`,
## returning the potted block's raw id or 0 (air) if the item has no potted
## form. Upstream wraps the result in a `BlockId` newtype (`BlockId::new_or_air`);
## that type lives in the still-unported block registry, so this returns the
## raw uint16 id directly - callers should wrap it once BlockId exists.
##
## Run with `nimony c -r src/data_codegen/gen_flower_pot_transformations.nim`
## from the repo root.

import std/syncio
import codegenutil

const OutPath = "src/generated/flower_pot_transformations.nim"

proc build(assetsPath: string): string =
  let pairs = readIntIntMapSorted(assetsPath & "/flower_pot_transformations.json")

  var s = "## GENERATED by src/data_codegen/gen_flower_pot_transformations.nim - do not edit by hand.\n\n"
  s.add("proc getPottedItem*(itemId: uint16): uint16 =\n")
  s.add("  ## Returns the potted-block raw id for `itemId`, or 0 (air) if it has\n")
  s.add("  ## no potted form. TODO: wrap in `BlockId` once the block registry is ported\n")
  s.add("  ## (upstream: `BlockId::new_or_air(raw_id)`).\n")
  s.add("  case itemId\n")
  for (itemId, pottedId) in pairs:
    s.add("  of " & $itemId & "'u16: " & $pottedId & "'u16\n")
  s.add("  else: 0'u16\n")

  s

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
