## Port of tools/pumpkin-codegen/src/block.rs, SCOPED per directive: only
## each block's flat scalar fields (id/name/translationKey/hardness/
## blastResistance/mapColor/itemId/defaultStateId), NOT the full
## property-permutation `states[]` array (each block can have many numbered
## states, one per property-value combination - e.g. a stairs block's
## facing x half x shape combinations) or the `collision_shapes`/
## `outline_shapes` indices into the separate top-level `shapes` array.
## That's real structural work deserving its own pass once something
## downstream actually needs per-state collision data; this table alone
## already lets src/world/palette.nim's block-state ids resolve to a real
## block name instead of an opaque uint32, which is the immediately useful
## part for src/server/block/, src/inventory/itemstub.nim, etc.
##
## `assets/blocks.json` is a JSON object with keys `block_entity_types`
## (array, ignored here), `shapes` (array, ignored here), and `blocks`
## (the array this generator reads).

import std/[json, syncio, algorithm]
import codegenutil

type
  BlockEntry = object
    id: int
    name: string
    translationKey: string
    hardness: float
    blastResistance: float
    mapColor: int
    itemId: int
    defaultStateId: int

proc readBlocks(path: string): seq[BlockEntry] =
  var tree = parseFile(path)
  let obj = root(tree)
  result = @[]
  for topKey, topVal in obj.pairs():
    if topKey != "blocks":
      continue
    for elem in topVal.items():
      var entry = BlockEntry(id: 0, name: "", translationKey: "", hardness: 0.0,
                              blastResistance: 0.0, mapColor: 0, itemId: 0,
                              defaultStateId: 0)
      for k, v in elem.pairs():
        case k
        of "id": entry.id = int(v.getInt())
        of "name": entry.name = v.getStr()
        of "translation_key": entry.translationKey = v.getStr()
        of "hardness": entry.hardness = v.getFloat()
        of "blast_resistance": entry.blastResistance = v.getFloat()
        of "map_color": entry.mapColor = int(v.getInt())
        of "item_id": entry.itemId = int(v.getInt())
        of "default_state_id": entry.defaultStateId = int(v.getInt())
        else: discard
      result.add(entry)
  result.sort(proc(a, b: BlockEntry): int = cmp(a.id, b.id))

proc esc(s: string): string =
  ## Minimal string-literal escaper; block translation keys/names are plain
  ## ASCII identifiers in practice, but escape `"`/`\` defensively anyway.
  result = ""
  for ch in s:
    if ch == '"' or ch == '\\':
      result.add('\\')
    result.add(ch)

proc main() =
  let blocks = readBlocks("../upstream-ref/assets/blocks.json")
  var s = "## Generated by src/data_codegen/gen_block.nim from assets/blocks.json.\n"
  s.add("## SCOPED: flat per-block fields only - no states[]/property\n")
  s.add("## permutation table, no collision/outline shape indices. See\n")
  s.add("## gen_block.nim's doc comment.\n\n")
  s.add("type\n  Block* = object\n    id*: int\n    name*: string\n")
  s.add("    translationKey*: string\n    hardness*: float\n")
  s.add("    blastResistance*: float\n    mapColor*: int\n    itemId*: int\n")
  s.add("    defaultStateId*: int\n\n")
  s.add("let AllBlocks*: seq[Block] = @[\n")
  for b in blocks:
    s.add("  Block(id: " & $b.id & ", name: \"" & esc(b.name) &
          "\", translationKey: \"" & esc(b.translationKey) &
          "\", hardness: " & $b.hardness & ", blastResistance: " &
          $b.blastResistance & ", mapColor: " & $b.mapColor &
          ", itemId: " & $b.itemId & ", defaultStateId: " &
          $b.defaultStateId & "),\n")
  s.add("]\n\n")
  s.add("proc blockById*(id: int): (bool, Block) =\n")
  s.add("  for b in AllBlocks:\n    if b.id == id: return (true, b)\n")
  s.add("  (false, Block())\n\n")
  s.add("proc blockByName*(name: string): (bool, Block) =\n")
  s.add("  for b in AllBlocks:\n    if b.name == name: return (true, b)\n")
  s.add("  (false, Block())\n")
  try:
    writeFile("../minecraft-server/src/generated/blockdata.nim", s)
  except ErrorCode as e:
    echo "writeFile failed: " & $e
  echo "wrote " & $blocks.len & " blocks"

main()
