## Port of tools/codegen/src/scoreboard_slot.rs - emits the
## `ScoreboardDisplaySlot` enum from `assets/scoreboard_display_slot.json`
## (a flat string array).

import std/syncio
import codegenutil

const OutPath = "src/generated/scoreboard_slot.nim"

proc build(assetsPath: string): string =
  let slots = readStringArray(assetsPath & "/scoreboard_display_slot.json")

  result = "## GENERATED by src/data_codegen/gen_scoreboard_slot.nim - do not edit by hand.\n\n"
  result.add("type\n  ScoreboardDisplaySlot* = enum\n")
  for s in slots:
    result.add("    sds" & toPascalCase(s) & "\n")

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
