## Port of tools/codegen/src/trim_material.rs. Directory-of-JSON-files shape,
## with a `palette_id` top-level field and a nested `description.color`/
## `description.translate` object (both `Option<String>`, defaulting to ""
## when absent - matches upstream's `.as_deref().unwrap_or("")`).
##
## Run with `nimony c -r src/data_codegen/gen_trim_material.nim` from the
## repo root.

import std/[syncio, paths]
import codegenutil

const OutPath = "src/generated/trim_material.nim"

proc build(dir: Path): string =
  let entries = listJsonStems(dir)
  var names: seq[string] = @[]
  var paletteIds, colors, translationKeys: seq[string] = @[]
  for (stem, p) in entries:
    names.add(stem)
    paletteIds.add(jsonStringField(p, "palette_id"))
    colors.add(jsonNestedStringField(p, "description", "color"))
    translationKeys.add(jsonNestedStringField(p, "description", "translate"))

  var s = "## GENERATED by src/data_codegen/gen_trim_material.nim - do not edit by hand.\n\n"
  s.add("type\n  TrimMaterial* = enum\n")
  for n in names:
    s.add("    tm" & toPascalCase(n) & "\n")
  s.add("\n")

  s.add("proc trimMaterialFromName*(name: string): (bool, TrimMaterial) =\n")
  s.add("  case name\n")
  for n in names:
    s.add("  of \"minecraft:" & n & "\", \"" & n & "\": (true, tm" & toPascalCase(n) & ")\n")
  s.add("  else: (false, tm" & toPascalCase(names[0]) & ")\n\n")

  s.add("proc id*(v: TrimMaterial): uint32 =\n")
  s.add("  uint32(ord(v))\n\n")

  s.add("proc toName*(v: TrimMaterial): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of tm" & toPascalCase(n) & ": \"" & n & "\"\n")
  s.add("\n")

  s.add("proc assetId*(v: TrimMaterial): string =\n")
  s.add("  case v\n")
  for n in names:
    s.add("  of tm" & toPascalCase(n) & ": \"minecraft:" & n & "\"\n")
  s.add("\n")

  s.add("proc paletteId*(v: TrimMaterial): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of tm" & toPascalCase(n) & ": \"" & paletteIds[i] & "\"\n")
  s.add("\n")

  s.add("proc color*(v: TrimMaterial): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of tm" & toPascalCase(n) & ": \"" & colors[i] & "\"\n")
  s.add("\n")

  s.add("proc translationKey*(v: TrimMaterial): string =\n")
  s.add("  case v\n")
  for i, n in names:
    s.add("  of tm" & toPascalCase(n) & ": \"" & translationKeys[i] & "\"\n")
  s.add("\n")

  s.add("const AllTrimMaterials*: array[" & $names.len & ", TrimMaterial] = [\n")
  for n in names:
    s.add("  tm" & toPascalCase(n) & ",\n")
  s.add("]\n")

  s

when isMainModule:
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/trim_material")
  try:
    let generated = build(dir)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
