## Port of tools/pumpkin-codegen/src/potion_brewing.rs's brewing-recipe
## half (upstream's `build()` also emits empty `ITEM_RECIPES`/
## `POTION_RECIPES` const arrays - always `[]` today, upstream's own
## comment says so, so this only emits `BREWING_RECIPES`).
##
## Scoped down from upstream: item/potion references become plain
## lowercase snake_case name strings (matching `src/generated/item.nim`'s
## `name` field convention) rather than `&'static Item`/`&'static Potion`
## references - no `Potion` table exists in this port yet (the
## `potion.rs` generator was found transitively blocked on unported
## `attributes`/`data_component_impl` types by an earlier fork), and
## linking against real `Item` entries would need a lookup helper this
## generator doesn't have reason to duplicate. A future pass can resolve
## these name strings against `item.nim`/a real `Potion` table once one
## exists.

import std/[json, paths, strutils, syncio]
import codegenutil

type
  BrewingRecipe* = object
    fromItem*: string
    fromPotion*: string
    ingredient*: string
    toItem*: string
    toPotion*: string

proc stripMc(s: string): string =
  if s.startsWith("minecraft:"): s[10 .. ^1] else: s

proc jsonNested(n: JsonNode, keys: varargs[string]): (bool, JsonNode) =
  ## Walks a chain of object keys from `n`, using `pairs` at each level
  ## (never `{}`, which crashes at runtime on a missing key - see
  ## `jsonTryGet`'s doc comment for the same trap at the tree-root level;
  ## this is the node-level equivalent, since brewing recipes need 2-3
  ## levels of nesting `jsonTryGet`/`jsonNestedStringField` don't cover).
  var cur = n
  for key in keys:
    if kind(cur) != JObject:
      return (false, cur)
    var found = false
    for k, v in pairs(cur):
      if k == key:
        cur = v
        found = true
        break
    if not found:
      return (false, cur)
  (true, cur)

proc parseBrewingRecipe(jsonPath: string): BrewingRecipe =
  var tree = parseFile(jsonPath)
  let root = root(tree)

  let (foundFromItem, fromItemNode) = jsonNested(root, "input", "item")
  let (foundFromPotion, fromPotionNode) = jsonNested(root, "input", "potion_contents", "potions")
  let (foundIngredient, ingredientNode) = jsonNested(root, "reagent", "item")
  let (foundToItem, toItemNode) = jsonNested(root, "output", "id")
  let (foundToPotion, toPotionNode) = jsonNested(root, "output", "components", "minecraft:potion_contents", "potion")

  result = BrewingRecipe(
    fromItem: if foundFromItem: stripMc(getStr(fromItemNode)) else: "",
    fromPotion: if foundFromPotion: stripMc(getStr(fromPotionNode)) else: "",
    ingredient: if foundIngredient: stripMc(getStr(ingredientNode)) else: "",
    toItem: if foundToItem: stripMc(getStr(toItemNode)) else: "",
    toPotion: if foundToPotion: stripMc(getStr(toPotionNode)) else: "",
  )

proc readBrewingRecipesSorted(dir: Path): seq[BrewingRecipe] =
  ## Port of upstream's `entries.sort_by_key(|e| e.path())`. Reuses
  ## `listJsonStems`'s already-correct path-collection (nesting
  ## `readFile`/`parseFile` inside a `try` inside a `walkDir` loop is a
  ## known Nimony C-codegen bug, see NIMONY-COMPILER-BUGS.md - avoided
  ## the same way every other per-directory generator here does).
  let stems = listJsonStems(dir)
  result = @[]
  for i in 0 ..< stems.len:
    result.add(parseBrewingRecipe($stems[i][1]))

proc generatePotionBrewing*(assetsDir, outPath: string) =
  let recipes = readBrewingRecipesSorted(path(assetsDir & "/datapack/data/minecraft/recipe/brewing"))
  var src = "## Generated by src/data_codegen/gen_potion_brewing.nim from " &
    "upstream/tools/pumpkin-codegen/src/potion_brewing.rs + assets/datapack/data/minecraft/recipe/brewing/*.json\n" &
    "## Do not edit by hand.\n\n" &
    "type\n" &
    "  BrewingRecipe* = object\n" &
    "    fromItem*: string\n" &
    "    fromPotion*: string\n" &
    "    ingredient*: string\n" &
    "    toItem*: string\n" &
    "    toPotion*: string\n\n" &
    "proc allBrewingRecipes*(): seq[BrewingRecipe] =\n" &
    "  result = @[]\n"
  for r in recipes:
    src.add("  result.add(BrewingRecipe(fromItem: \"" & r.fromItem &
      "\", fromPotion: \"" & r.fromPotion & "\", ingredient: \"" & r.ingredient &
      "\", toItem: \"" & r.toItem & "\", toPotion: \"" & r.toPotion & "\"))\n")
  try:
    writeFile(outPath, src)
  except ErrorCode as e:
    echo "generatePotionBrewing: writeFile failed: " & $e

when isMainModule:
  ## Run from the repo root, matching every other gen_*.nim's own
  ## `when isMainModule` convention (see gen_biome.nim's `main()`).
  generatePotionBrewing("../upstream-ref/assets", "src/generated/potion_brewing.nim")
