## Port of tools/codegen/src/particle.rs.
## Flat string array -> enum, same shape as sound_category, plus
## index-based fromId/toId (the enum's declaration order IS the id order,
## matching upstream's `*self as u16` discriminant-cast semantics).
##
## Run with `nimony c -r src/data_codegen/gen_particle.nim` from the
## repo root.

import std/syncio
import codegenutil

const OutPath = "src/generated/particle.nim"

proc build(path: string): string =
  let particles = readStringArray(path)

  var s = "## GENERATED by src/data_codegen/gen_particle.nim - do not edit by hand.\n\n"
  s.add("type\n  Particle* = enum\n")
  for p in particles:
    s.add("    pt" & toPascalCase(p) & "\n")
  s.add("\n")

  s.add("proc particleFromName*(name: string): (bool, Particle) =\n")
  s.add("  case name\n")
  for p in particles:
    s.add("  of \"" & p & "\": (true, pt" & toPascalCase(p) & ")\n")
  s.add("  else: (false, pt" & toPascalCase(particles[0]) & ")\n\n")

  s.add("proc particleToName*(p: Particle): string =\n")
  s.add("  case p\n")
  for p in particles:
    s.add("  of pt" & toPascalCase(p) & ": \"" & p & "\"\n")
  s.add("\n")

  s.add("proc particleFromId*(id: uint16): (bool, Particle) =\n")
  s.add("  case id\n")
  for i, p in particles:
    s.add("  of " & $i & "'u16: (true, pt" & toPascalCase(p) & ")\n")
  s.add("  else: (false, pt" & toPascalCase(particles[0]) & ")\n\n")

  s.add("proc particleToId*(p: Particle): uint16 =\n")
  s.add("  uint16(ord(p))\n")

  s

when isMainModule:
  let jsonPath = "../upstream-ref/assets/particles.json"
  try:
    let generated = build(jsonPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
