## Generator for `Instrument`.
## Port of upstream/tools/codegen/src/instrument.rs
## Depends on `Sound` (src/generated/sound.nim, from gen_sound.nim) for the
## `sound()` accessor.

import std/[syncio, paths, strutils]
import codegenutil

proc main() =
  let dir = path("../upstream-ref/assets/datapack/data/minecraft/instrument")
  let entries = listJsonStems(dir)

  var variants = ""
  var fromNameArms = ""
  var toNameArms = ""
  var assetIdArms = ""
  var soundArms = ""
  var durSecArms = ""
  var durTicksArms = ""
  var rangeArms = ""
  var translationKeyArms = ""
  var allElements = ""

  for (name, path) in entries:
    let v = "in" & toPascalCase(name)
    let namespaced = "minecraft:" & name
    var translate = jsonNestedStringField(path, "description", "translate")
    if translate == "":
      translate = "instrument.minecraft." & name
    let rangeVal = jsonFloatField(path, "range", 0.0)
    let useDurationSec = jsonFloatField(path, "use_duration", 0.0)
    let useDurationTicks = int(useDurationSec * 20.0 + 0.5)
    var soundEvent = jsonStringField(path, "sound_event")
    if soundEvent.startsWith("minecraft:"):
      soundEvent = soundEvent[10 .. ^1]
    let soundIdent = "sd" & toPascalCase(soundEvent)

    variants.add("    " & v & "\n")
    fromNameArms.add("  of \"" & namespaced & "\", \"" & name & "\": (true, " & v & ")\n")
    toNameArms.add("  of " & v & ": \"" & name & "\"\n")
    assetIdArms.add("  of " & v & ": \"" & namespaced & "\"\n")
    soundArms.add("  of " & v & ": " & soundIdent & "\n")
    durSecArms.add("  of " & v & ": " & $useDurationSec & "'f32\n")
    durTicksArms.add("  of " & v & ": " & $useDurationTicks & "'u32\n")
    rangeArms.add("  of " & v & ": " & $rangeVal & "'f32\n")
    translationKeyArms.add("  of " & v & ": \"" & translate & "\"\n")
    allElements.add("  " & v & ",\n")

  let firstVariant = if entries.len > 0: "in" & toPascalCase(entries[0][0]) else: "inNone"

  let output = "## The `Instrument` registry (id = declaration order).\n" &
    "## Generated by gen_instrument.nim from upstream/assets/datapack/data/minecraft/instrument/ - do not edit by hand.\n\n" &
    "import sound\n\n" &
    "type\n" &
    "  Instrument* = enum\n" &
    variants & "\n" &
    "proc fromName*(name: string): (bool, Instrument) =\n" &
    "  case name\n" & fromNameArms &
    "  else: (false, " & firstVariant & ")\n\n" &
    "proc id*(i: Instrument): uint32 = uint32(ord(i))\n\n" &
    "proc toName*(i: Instrument): string =\n" &
    "  case i\n" & toNameArms & "\n" &
    "proc assetId*(i: Instrument): string =\n" &
    "  case i\n" & assetIdArms & "\n" &
    "proc sound*(i: Instrument): Sound =\n" &
    "  case i\n" & soundArms & "\n" &
    "proc useDurationSeconds*(i: Instrument): float32 =\n" &
    "  case i\n" & durSecArms & "\n" &
    "proc useDurationTicks*(i: Instrument): uint32 =\n" &
    "  case i\n" & durTicksArms & "\n" &
    "proc range*(i: Instrument): float32 =\n" &
    "  case i\n" & rangeArms & "\n" &
    "proc translationKey*(i: Instrument): string =\n" &
    "  case i\n" & translationKeyArms & "\n" &
    "const All* = [\n" & allElements & "]\n"

  try:
    writeFile("src/generated/instrument.nim", output)
  except ErrorCode as e:
    echo "write failed: " & $e
  echo "wrote src/generated/instrument.nim (" & $entries.len & " instruments)"

main()
