## Port of tools/codegen/src/meta_data_type.rs.
##
## Reads `meta_data_type.json` (a flat name->i32 map), canonicalizes a
## handful of synonym names down to one canonical spelling (some data-type
## names changed between Minecraft versions; both old and new names appear
## in the JSON and must collapse to the same id), then emits named
## `MetaDataType` constants plus alias constants for the non-canonical
## names.
##
## Run with `nimony c -r src/data_codegen/gen_meta_data_type.nim` from the
## repo root.

import std/[syncio, strutils, algorithm]
import codegenutil

const OutPath = "src/generated/meta_data_type.nim"

proc canonicalizeTypeName(name: string): string =
  case name
  of "integer", "int": "int"
  of "entity_pose", "pose": "pose"
  of "facing", "direction": "direction"
  of "text_component", "component": "component"
  of "optional_text_component", "optional_component": "optional_component"
  of "optional_int", "optional_unsigned_int": "optional_unsigned_int"
  of "vector_3f", "vector3": "vector3"
  of "quaternion_f", "quaternion": "quaternion"
  of "rotation", "rotations": "rotations"
  of "particle_list", "particles": "particles"
  of "copper_golem_state", "weathering_copper_state": "weathering_copper_state"
  of "profile", "resolvable_profile": "resolvable_profile"
  of "arm", "humanoid_arm": "humanoid_arm"
  else: name

proc build(path: string): string =
  let parsed = readStringIntMapSorted(path)

  # Canonicalize, de-duplicating by canonical name (BTreeMap::insert
  # semantics in the Rust source: later entries overwrite earlier ones for
  # the same key - since `parsed` is already sorted ascending by the raw
  # name, this matches iterating `parsed` in order and inserting).
  var canonNames: seq[string] = @[]
  var canonIds: seq[int] = @[]
  for (name, id) in parsed:
    let canon = canonicalizeTypeName(name)
    var found = -1
    for i, n in canonNames:
      if n == canon:
        found = i
        break
    if found >= 0:
      canonIds[found] = id
    else:
      canonNames.add(canon)
      canonIds.add(id)

  # Upstream's `handlers_map` is itself a BTreeMap<String, i32>, so final
  # emission order is ascending canonical-name order, not raw-insertion
  # order. Sort tuples directly (rather than an index array via a capturing
  # lambda) since `algorithm.sort`'s comparator param isn't `.closure.`-typed.
  var canonPairs: seq[(string, int)] = @[]
  for i in 0 ..< canonNames.len:
    canonPairs.add((canonNames[i], canonIds[i]))
  canonPairs.sort(proc(a, b: (string, int)): int = cmp(a[0], b[0]))

  var s = "## GENERATED by src/data_codegen/gen_meta_data_type.nim - do not edit by hand.\n\n"
  s.add("type\n  MetaDataType* = object\n    id*: int32\n\n")
  for (canonName, id) in canonPairs:
    s.add("const " & toUpperAscii(canonName) & "*: MetaDataType = MetaDataType(id: " & $id & ")\n")

  # Alias constants: each non-canonical synonym name from the match table
  # gets its own constant equal to the canonical one, mirroring upstream's
  # `pub const INTEGER: MetaDataType = Self::INT;` block. This list is the
  # same synonym table as canonicalizeTypeName, restated as (alias, canonical)
  # pairs in upstream's own emission order.
  const aliases = [
    ("INTEGER", "int"), ("ENTITY_POSE", "pose"), ("FACING", "direction"),
    ("TEXT_COMPONENT", "component"), ("OPTIONAL_TEXT_COMPONENT", "optional_component"),
    ("OPTIONAL_INT", "optional_unsigned_int"), ("VECTOR_3F", "vector3"),
    ("QUATERNION_F", "quaternion"), ("ROTATION", "rotations"),
    ("PARTICLE_LIST", "particles"), ("COPPER_GOLEM_STATE", "weathering_copper_state"),
    ("PROFILE", "resolvable_profile"), ("ARM", "humanoid_arm"),
  ]
  s.add("\n")
  for (aliasName, canonKey) in aliases:
    s.add("const " & aliasName & "*: MetaDataType = " & toUpperAscii(canonKey) & "\n")

  s

when isMainModule:
  let jsonPath = "../upstream-ref/assets/meta_data_type.json"
  try:
    let generated = build(jsonPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
