## Port of tools/codegen/src/villager.rs's `VillagerDataJson` load, scoped
## way down. Upstream's real `build()` also: walks a `trade_set` datapack
## directory and a `tags/villager_trade` tag directory, recursively resolves
## tag references (`resolve_trade_tag`, with cycle detection via a visited
## set) into concrete trade lists, and builds a full weighted trade table
## per profession/level. That's a genuine recursive resolution algorithm
## with real edge cases (cycles, tag-vs-literal-tag disambiguation), not a
## "missing helper" - a real follow-up task, not attempted here.
##
## What IS ported: the flat, non-recursive parts of `villager_data.json` -
## `professions` (name/requested_items/work_sound) and `types` (villager
## biome-variant name -> texture namespace). `secondary_poi` and
## `trade_sets` (the level->tag-id map, needed by the deferred resolution
## step) are read from the source JSON but not emitted.
##
## Run with `nimony c -r src/data_codegen/gen_villager.nim` from the repo
## root.

import std/[json, syncio, assertions]
import codegenutil

const OutPath = "src/generated/villager.nim"

type ProfessionEntry = object
  name: string
  translate: string
  requestedItems: seq[string]
  workSound: string # "" = upstream's None

proc readStringSeqField(obj: JsonNode, key: string): seq[string] =
  result = @[]
  for k, v in obj.pairs():
    if k == key and v.kind == JArray:
      for item in v.items():
        result.add(item.getStr())

proc readOptStringField(obj: JsonNode, key: string): string =
  result = ""
  for k, v in obj.pairs():
    if k == key and v.kind == JString:
      result = v.getStr()

proc build(jsonPath: string): string =
  var tree = parseFile(jsonPath)
  let obj = root(tree)

  var professions: seq[ProfessionEntry] = @[]
  var typeNames, typeNamespaces: seq[string] = @[]

  for topKey, topVal in obj.pairs():
    if topKey == "professions":
      for profName, profVal in topVal.pairs():
        var entry = ProfessionEntry(name: profName)
        for k, v in profVal.pairs():
          if k == "name" and v.kind == JObject:
            entry.translate = readOptStringField(v, "translate")
          elif k == "requested_items":
            entry.requestedItems = readStringSeqField(profVal, "requested_items")
          elif k == "work_sound":
            entry.workSound = readOptStringField(profVal, "work_sound")
        professions.add(entry)
    elif topKey == "types":
      for typeName, typeVal in topVal.pairs():
        typeNames.add(typeName)
        typeNamespaces.add(typeVal.getStr())

  var s = "## GENERATED by src/data_codegen/gen_villager.nim - do not edit by hand.\n\n"
  s.add("type\n  VillagerProfession* = object\n")
  s.add("    name*: string\n    translate*: string\n    requestedItems*: seq[string]\n    workSound*: string\n\n")

  s.add("proc allVillagerProfessions*(): seq[VillagerProfession] =\n")
  s.add("  result = @[]\n")
  for p in professions:
    s.add("  result.add(VillagerProfession(name: \"" & p.name & "\", translate: \"" & p.translate & "\", requestedItems: @[")
    for i, item in p.requestedItems:
      if i > 0: s.add(", ")
      s.add("\"" & item & "\"")
    s.add("], workSound: \"" & p.workSound & "\"))\n")
  s.add("\n")

  s.add("proc villagerTypeNames*(): seq[string] =\n")
  s.add("  @[")
  for i, n in typeNames:
    if i > 0: s.add(", ")
    s.add("\"" & n & "\"")
  s.add("]\n\n")

  s.add("proc villagerTypeNamespace*(name: string): string =\n")
  s.add("  case name\n")
  for i, n in typeNames:
    s.add("  of \"" & n & "\": \"" & typeNamespaces[i] & "\"\n")
  s.add("  else: \"\"\n")

  s

when isMainModule:
  try:
    let generated = build("../upstream-ref/assets/villager_data.json")
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
