## Port of tools/codegen/src/attributes.rs.
##
## Reads `assets/attributes.json` (a name -> {id, default_value} map),
## sorts by id (matching upstream's explicit `sort_by_key`), and emits one
## named constant per attribute plus an `ALL` array - Rust's `pub const
## FOO: Self = Self{...}` associated-constant pattern becomes a plain Nim
## `const` here, since Nimony has no impl blocks to attach them to.
##
## Run with `nimony c -r src/data_codegen/gen_attributes.nim` from the
## minecraft-server repo root.

import std/[syncio, json, algorithm]
import codegenutil

const OutPath = "src/generated/attributes.nim"

type
  AttrEntry = object
    name: string
    id: int
    defaultValue: float

proc readAttributes(path: string): seq[AttrEntry] =
  ## Port of `serde_json::from_str::<BTreeMap<String, Attributes>>(...)`,
  ## sorted by id per upstream's explicit `sort_by_key(|(_, raw)| raw.id)`.
  var tree = parseFile(path)
  let obj = root(tree)
  result = @[]
  for name, val in obj.pairs():
    var entry = AttrEntry(name: name, id: 0, defaultValue: 0.0)
    for k, v in val.pairs():
      case k
      of "id": entry.id = int(v.getInt())
      of "default_value": entry.defaultValue = v.getFloat()
      else: discard
    result.add(entry)
  result.sort(proc(a, b: AttrEntry): int = cmp(a.id, b.id))

proc build(assetsPath: string): string =
  let attrs = readAttributes(assetsPath & "/attributes.json")

  var s = "## GENERATED by src/data_codegen/gen_attributes.nim - do not edit by hand.\n\n"
  s.add("type\n")
  s.add("  Attribute* = object\n")
  s.add("    id*: uint8\n")
  s.add("    defaultValue*: float64\n")
  s.add("    name*: string\n\n")

  for a in attrs:
    let constName = toShoutySnakeCase(a.name)
    s.add("const " & constName & "*: Attribute = Attribute(id: " & $a.id &
      "'u8, defaultValue: " & $a.defaultValue &
      "'f64, name: \"minecraft:" & a.name & "\")\n")
  s.add("\n")

  s.add("proc allAttributes*(): seq[Attribute] =\n")
  s.add("  @[\n")
  for a in attrs:
    s.add("    " & toShoutySnakeCase(a.name) & ",\n")
  s.add("  ]\n")

  s

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
