## Generator for `MapColor`.
## Port of upstream/tools/codegen/src/map_color.rs

import std/syncio
import std/tables
import codegenutil

proc main() =
  let colors = readMapColors("../upstream-ref/assets/map_colors.json")

  var constants = ""
  var allElements = ""
  var idMatchArms = ""
  var nameMatchArms = ""
  var seenNames = initTable[string, bool]()

  for entry in colors:
    let constName =
      if entry.name == "none": "NONE_" & $entry.id
      else: toShoutySnakeCase(entry.name)

    constants.add("const " & constName & "* = MapColor(id: " & $entry.id &
      ", name: \"" & entry.name & "\", col: " & $entry.col &
      ", r: " & $entry.r & ", g: " & $entry.g & ", b: " & $entry.b & ")\n")
    allElements.add("  " & constName & ",\n")
    idMatchArms.add("  of " & $entry.id & ": (true, " & constName & ")\n")
    if not seenNames.hasKey(entry.name):
      seenNames[entry.name] = true
      nameMatchArms.add("  of \"" & entry.name & "\": (true, " & constName & ")\n")

  let firstConst =
    if colors.len > 0 and colors[0].name == "none": "NONE_" & $colors[0].id
    elif colors.len > 0: toShoutySnakeCase(colors[0].name)
    else: "NONE_0"

  let output = "## The `MapColor` registry.\n" &
    "## Generated by gen_map_color.nim from upstream/assets/map_colors.json - do not edit by hand.\n\n" &
    "type\n" &
    "  MapColor* = object\n" &
    "    id*: int\n" &
    "    name*: string\n" &
    "    col*: int\n" &
    "    r*, g*, b*: int\n\n" &
    constants & "\n" &
    "const All* = [\n" & allElements & "]\n\n" &
    "proc fromId*(id: int): (bool, MapColor) =\n" &
    "  case id\n" & idMatchArms &
    "  else: (false, " & firstConst & ")\n\n" &
    "proc fromName*(name: string): (bool, MapColor) =\n" &
    "  case name\n" & nameMatchArms &
    "  else: (false, " & firstConst & ")\n"

  try:
    writeFile("src/generated/map_color.nim", output)
  except ErrorCode as e:
    echo "write failed: " & $e
  echo "wrote src/generated/map_color.nim (" & $colors.len & " colors)"

main()
