## Generates src/generated/test_instance.nim: a lookup table from
## resource id (and, for the default "minecraft" namespace, the bare id
## too) to the real on-disk path of the `.json` game-test-instance
## definition it names.
## Port of tools/pumpkin-codegen/src/test_instance.rs.
##
## Same shape as gen_template_bytes.nim (which this is a near-mirror of,
## the same way the two upstream Rust files are near-mirrors of each
## other), including the same reasons for recording paths instead of
## embedding file contents, and the same iterative-not-recursive
## directory walk to avoid the `var Table[...]` out-param bug documented
## in NIMONY-COMPILER-BUGS.md and in gen_template_bytes.nim's doc comment.
##
## Run with `nimony c -r src/data_codegen/gen_test_instance.nim` from the
## repo root.

import std/[syncio, paths, dirs, algorithm, tables, strutils]
import codegenutil

const VanillaPackRoot = "../upstream-ref/assets/datapack"
const ContainerDir = "../upstream-ref/assets/tests/datapacks"
const DefaultNamespace = "minecraft"

type
  TestInstanceEntry = object
    resourceId: string
    bareId: string
    isDefault: bool
    relPath: string

proc toForwardSlashes(s: string): string =
  result = newString(s.len)
  for i, c in s:
    result[i] = (if c == '\\': '/' else: c)

proc baseName(p: Path): string =
  var base = $p
  let slashIdx = max(lastIndexOf(base, '/'), lastIndexOf(base, '\\'))
  if slashIdx >= 0:
    base = base[(slashIdx + 1) .. ^1]
  base

proc listDirSorted(dir: Path): seq[(string, Path, bool)] =
  var entries: seq[(string, Path, bool)] = @[]
  try:
    for kind, entryPath in walkDir(dir):
      entries.add((baseName(entryPath), entryPath, kind == pcDir))
  except ErrorCode:
    discard
  entries.sort(proc(a, b: (string, Path, bool)): int = cmp(a[0], b[0]))
  entries

proc scanTestInstanceDir(dir: Path, namespace: string): seq[TestInstanceEntry] =
  result = @[]
  var stack: seq[(Path, string)] = @[(dir, "")]
  while stack.len > 0:
    let (curDir, prefix) = stack.pop()
    for (name, entryPath, isDir) in listDirSorted(curDir):
      if isDir:
        let newPrefix = if prefix.len == 0: name else: prefix & "/" & name
        stack.add((entryPath, newPrefix))
        continue
      if not name.endsWith(".json"):
        continue
      let stem = name[0 ..< (name.len - 5)]
      let id = if prefix.len == 0: stem else: prefix & "/" & stem
      let resourceId = namespace & ":" & id
      result.add(TestInstanceEntry(
        resourceId: resourceId,
        bareId: id,
        isDefault: namespace == DefaultNamespace,
        relPath: toForwardSlashes($entryPath)))

proc main() =
  var packs: seq[Path] = @[path(VanillaPackRoot)]
  for (_, fullPath, isDir) in listDirSorted(path(ContainerDir)):
    if isDir:
      packs.add(fullPath)

  var results = initTable[string, TestInstanceEntry]()
  for packPath in packs:
    let dataDir = packPath / path("data")
    for (namespace, nsDir, isDir) in listDirSorted(dataDir):
      if not isDir: continue
      let tiDir = nsDir / path("test_instance")
      for e in scanTestInstanceDir(tiDir, namespace):
        results[e.resourceId] = e

  var keys: seq[string] = @[]
  for k in results.keys:
    keys.add(k)
  keys.sort(proc(a, b: string): int = cmp(a, b))

  var output = "## Generated by src/data_codegen/gen_test_instance.nim - do not edit by hand.\n"
  output.add("## Maps a game-test instance's resource id (and, for the default\n")
  output.add("## \"minecraft\" namespace, its bare id too) to the real on-disk path of\n")
  output.add("## its `.json` definition. Paths are recorded rather than contents\n")
  output.add("## embedded - see gen_template_bytes.nim's doc comment for why.\n\n")
  output.add("type\n")
  output.add("  TestInstancePathEntry* = object\n")
  output.add("    resourceId*: string\n")
  output.add("    bareId*: string\n")
  output.add("    isDefault*: bool\n")
  output.add("    relPath*: string\n\n")
  output.add("let testInstancePaths*: seq[TestInstancePathEntry] = @[\n")
  for k in keys:
    var e: TestInstanceEntry
    try:
      e = results[k]
    except ErrorCode:
      continue
    output.add("  TestInstancePathEntry(resourceId: \"" & e.resourceId &
      "\", bareId: \"" & e.bareId & "\", isDefault: " & $e.isDefault &
      ", relPath: \"" & e.relPath & "\"),\n")
  output.add("]\n\n")
  output.add("proc getTestInstancePath*(id: string): (bool, string) =\n")
  output.add("  for e in testInstancePaths:\n")
  output.add("    if e.resourceId == id or (e.isDefault and e.bareId == id):\n")
  output.add("      return (true, e.relPath)\n")
  output.add("  (false, \"\")\n")

  try:
    writeFile("src/generated/test_instance.nim", output)
    echo "wrote src/generated/test_instance.nim: ", keys.len, " test instances"
  except ErrorCode as e:
    echo "write failed: " & $e

main()
