## Port of tools/codegen/src/screen.rs - emits the `WindowType` enum from
## `assets/screens.json` (a flat string array).

import std/syncio
import codegenutil

const OutPath = "src/generated/screen.nim"

proc build(assetsPath: string): string =
  let screens = readStringArray(assetsPath & "/screens.json")

  result = "## GENERATED by src/data_codegen/gen_screen.nim - do not edit by hand.\n\n"
  result.add("type\n  WindowType* = enum\n")
  for s in screens:
    result.add("    wt" & toPascalCase(s) & "\n")

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
