## Generator for upstream/tools/pumpkin-codegen/src/context_provider.rs
## Run with: nimony c -r src/data_codegen/gen_context_provider.nim
##
## Walks `assets/datapack/data/minecraft/context_{int,float}_provider/`
## (one level of category subdirectory, e.g. `cooking/time_coal.json`),
## and embeds each JSON file's raw text (upstream does this with
## `include_str!` at Rust compile time) into lookup procs keyed by both
## the bare id (`cooking/time_coal`) and the namespaced id
## (`minecraft:cooking/time_coal`), plus a name-list proc for each kind -
## matching `get_context_int_provider_json`/`all_context_int_provider_names`
## and their float counterparts.

import std/json, std/paths, std/dirs, std/syncio, std/strutils, std/os, std/algorithm

const DefaultNamespace = "minecraft"

proc escapeNim(s: string): string =
  ## Nim/Nimony string-literal escaping for embedding raw file text.
  result = "\""
  for ch in s:
    case ch
    of '"': result.add("\\\"")
    of '\\': result.add("\\\\")
    of '\n': result.add("\\n")
    of '\r': result.add("\\r")
    else: result.add(ch)
  result.add("\"")

proc readOne(filePath: string): string =
  try:
    result = readFile(filePath)
  except ErrorCode as e:
    echo "readOne: readFile failed: " & $e
    result = ""

proc scanCategory(catPath: Path, category: string): seq[(string, string)] =
  var jsonFiles: seq[(string, string)] = @[]  # (id, filePath)
  try:
    for fileKind, filePath in walkDir(catPath):
      if fileKind != pcFile: continue
      let name = extractFilename($filePath)
      if not name.endsWith(".json"): continue
      let stem = name[0 ..< name.len - 5]
      let id = category & "/" & stem
      jsonFiles.add((id, $filePath))
  except ErrorCode as e:
    echo "scanCategory: walkDir failed: " & $e
  result = @[]
  for (id, filePath) in jsonFiles:
    result.add((id, readOne(filePath)))

proc scanProviderDir(dir: Path): seq[(string, string)] =
  ## Returns (id, rawJsonText) pairs, id = "category/stem", sorted by id
  ## (mirrors upstream's `BTreeMap<String, _>` insertion-then-iteration).
  result = @[]
  var categories: seq[(Path, string)] = @[]
  try:
    for catKind, catPath in walkDir(dir):
      if catKind != pcDir: continue
      categories.add((catPath, extractFilename($catPath)))
  except ErrorCode as e:
    echo "scanProviderDir: walkDir failed: " & $e
  for (catPath, category) in categories:
    for entry in scanCategory(catPath, category):
      result.add(entry)
  result.sort(proc(a, b: (string, string)): int = cmp(a[0], b[0]))

proc emitLookup(kindName: string, entries: seq[(string, string)]): string =
  result = "proc getContext" & kindName & "ProviderJson*(id: string): (bool, string) =\n"
  result &= "  case id\n"
  for (id, text) in entries:
    let qualified = DefaultNamespace & ":" & id
    result &= "  of " & escapeNim(qualified) & ", " & escapeNim(id) & ":\n"
    result &= "    (true, " & escapeNim(text) & ")\n"
  result &= "  else:\n    (false, \"\")\n\n"
  result &= "proc all" & kindName & "ProviderNames*(): seq[string] =\n  @["
  var first = true
  for (id, _) in entries:
    if not first: result &= ", "
    first = false
    result &= escapeNim(id)
  result &= "]\n"

let intDir = path("../upstream-ref/assets/datapack/data/minecraft/context_int_provider")
let floatDir = path("../upstream-ref/assets/datapack/data/minecraft/context_float_provider")

let intEntries = scanProviderDir(intDir)
let floatEntries = scanProviderDir(floatDir)

var output = "## Port of upstream/tools/pumpkin-codegen/src/context_provider.rs\n"
output &= "## Generated by src/data_codegen/gen_context_provider.nim - do not hand-edit.\n\n"
output &= emitLookup("Int", intEntries)
output &= "\n"
output &= emitLookup("Float", floatEntries)

try:
  writeFile("src/generated/context_provider.nim", output)
except ErrorCode as e:
  echo "writeFile failed: " & $e
echo "wrote src/generated/context_provider.nim: " & $intEntries.len & " int + " &
  $floatEntries.len & " float providers"
