## Scoped-down Nimony port of tools/pumpkin-codegen/src/noise_router.rs
## (3405 lines - the largest generator in the suite by a wide margin).
##
## Upstream's real job: read every worldgen/density_function/**/*.json file
## (a recursive expression-tree format - constants, noise samples,
## arithmetic combinators, splines, references to other named density
## functions), deduplicate identical subtrees by content hash into a flat
## node array, and emit a `proc_macro2::TokenStream` that builds the whole
## DAG as Rust `static` data with index-based cross-references. That's a
## real compiler-shaped problem (hash-consing, topological node ordering,
## a `SplineRepr` sub-format with its own recursive `values: Box<[Self]>`
## field) - not attempted here.
##
## IMPORTANT correction made while writing this file: `DensityFunctionRepr`
## itself is `#[serde(tag = "_class", content = "value")]` - its JSON tag
## field is `_class`, not the human-authored datapack format's `"type":
## "minecraft:noise"` style tag seen in the raw
## `assets/datapack/.../density_function/**/*.json` files (those use
## namespaced `minecraft:`-prefixed type strings and a flat/nested object
## shape with no `_class`/`value` wrapper at all). The two are DIFFERENT
## representations - `DensityFunctionRepr` deserializes some other,
## internal/precomputed JSON source this pass didn't locate, not the raw
## datapack files directly. Do not assume the `_class`/JSON-type mapping
## below has been verified against real on-disk data; it hasn't, since no
## real `_class`-tagged input was found. It IS verified as an internally
## consistent enum (fromJsonType/toJsonType round-trip for all 26 kinds).
##
## Scoped down per this port's established "table first, full semantics
## later" pattern (block.rs/item.rs, recipes.rs): this generator emits only
## `DensityFunctionKind`, the flat enum of the 26 node kinds
## `DensityFunctionRepr` distinguishes (upstream's src, lines 466-587),
## plus a name<->kind mapping. No tree structure, no evaluation, no spline
## support. A future pass building the real DAG needs a NON-self-recursive
## Nimony shape for the tree (e.g. a flat `seq[DensityFunctionNode]` with
## index-based child references, mirroring upstream's own post-hash-consing
## representation) rather than a directly self-recursive `case object`,
## which fails Nimony's C-codegen even when `nimony check` passes clean
## (see NIMONY-COMPILER-BUGS.md #3 at the repo root).
##
## Run with `nimony c -r src/data_codegen/gen_noise_router.nim` from the
## repo root.

import std/syncio

const OutPath = "src/generated/noise_router.nim"

## The 25 `DensityFunctionRepr` variant names, in upstream's declaration
## order (tools/pumpkin-codegen/src/noise_router.rs:466-587). Values with a
## `#[serde(rename(deserialize = "..."))]` are annotated below with the
## JSON `_type` string that actually selects them, since it differs from
## the Rust variant name for a few kinds (IntervalSelect keeps its name;
## Wrapper's JSON type is "Wrapping"; Binary's is "BinaryOperation"; Linear's
## is "LinearOperation"; Unary's is "UnaryOperation"; ClampedYGradient's is
## "YClampedGradient").
let Kinds: seq[(string, string)] = @[
  ("Beardifier", "Beardifier"),
  ("BlendAlpha", "BlendAlpha"),
  ("BlendOffset", "BlendOffset"),
  ("BlendDensity", "BlendDensity"),
  ("FindTopSurface", "FindTopSurface"),
  ("EndIslands", "EndIslands"),
  ("Noise", "Noise"),
  ("ShiftA", "ShiftA"),
  ("ShiftB", "ShiftB"),
  ("ShiftedNoise", "ShiftedNoise"),
  ("InterpolatedNoiseSampler", "InterpolatedNoiseSampler"),
  ("IntervalSelect", "IntervalSelect"),
  ("Wrapper", "Wrapping"),
  ("Constant", "Constant"),
  ("ClampedYGradient", "YClampedGradient"),
  ("Gradient", "Gradient"),
  ("DistanceToPoint", "DistanceToPoint"),
  ("Lerp", "Lerp"),
  ("Rounding", "Rounding"),
  ("Slice", "Slice"),
  ("Binary", "BinaryOperation"),
  ("Linear", "LinearOperation"),
  ("Unary", "UnaryOperation"),
  ("Clamp", "Clamp"),
  ("RangeChoice", "RangeChoice"),
  ("Spline", "Spline"),
]

proc build(): string =
  var s = "## GENERATED by src/data_codegen/gen_noise_router.nim - do not edit by hand.\n"
  s.add("## Scoped-down: node-kind enum only, no tree structure. See gen_noise_router.nim's\n")
  s.add("## doc comment for what's deferred and why.\n\n")
  s.add("type\n  DensityFunctionKind* = enum\n")
  for (name, _) in Kinds:
    s.add("    dfk" & name & "\n")
  s.add("\n")

  s.add("proc densityFunctionKindFromJsonType*(jsonType: string): (bool, DensityFunctionKind) =\n")
  s.add("  case jsonType\n")
  for (name, jsonType) in Kinds:
    s.add("  of \"" & jsonType & "\": (true, dfk" & name & ")\n")
  s.add("  else: (false, dfk" & Kinds[0][0] & ")\n\n")

  s.add("proc densityFunctionKindToJsonType*(k: DensityFunctionKind): string =\n")
  s.add("  case k\n")
  for (name, jsonType) in Kinds:
    s.add("  of dfk" & name & ": \"" & jsonType & "\"\n")

  s

when isMainModule:
  let generated = build()
  try:
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes, " & $Kinds.len & " kinds)"
  except ErrorCode as e:
    echo "generation failed: " & $e
