## Port of tools/codegen/src/entity_status.rs - emits the `EntityStatus`
## enum with explicit u8 discriminants from `assets/entity_statuses.json`
## (a name->id map). Rust's `BTreeMap` iterates in ascending key order;
## `readStringIntMapSorted` reproduces that so variant order matches
## upstream's emitted enum exactly.

import std/syncio
import codegenutil

const OutPath = "src/generated/entity_status.nim"

proc build(assetsPath: string): string =
  let events = readStringIntMapSorted(assetsPath & "/entity_statuses.json")

  result = "## GENERATED by src/data_codegen/gen_entity_status.nim - do not edit by hand.\n\n"
  result.add("type\n  EntityStatus* = enum\n")
  for (name, id) in events:
    result.add("    es" & toPascalCase(name) & " = " & $id & "\n")

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
