## Generator for `GameEvent`.
## Port of upstream/tools/codegen/src/game_event.rs

import std/syncio
import codegenutil

proc main() =
  let events = readStringArray("../upstream-ref/assets/game_event.json")

  var variants = ""
  var fromNameArms = ""
  var toNameArms = ""

  for event in events:
    let ident = toPascalCase(event)
    let namespaced = "minecraft:" & event
    variants.add("    gv" & ident & "\n")
    fromNameArms.add("  of \"" & event & "\", \"" & namespaced & "\": (true, gv" & ident & ")\n")
    toNameArms.add("  of gv" & ident & ": \"" & event & "\"\n")

  let output = """## The `GameEvent` registry.
## Generated by gen_game_event.nim from upstream/assets/game_event.json - do not edit by hand.

type
  GameEvent* = enum
""" & variants & """
proc name*(e: GameEvent): string =
  case e
""" & toNameArms & """
proc fromName*(name: string): (bool, GameEvent) =
  case name
""" & fromNameArms & """  else: (false, gv""" & toPascalCase(events[0]) & """)
"""
  try:
    writeFile("src/generated/game_event.nim", output)
  except ErrorCode as e:
    echo "write failed: " & $e
  echo "wrote src/generated/game_event.nim (" & $events.len & " events)"

main()
