## Port of tools/codegen/src/entity_pose.rs - emits the `EntityPose` enum
## from `assets/entity_pose.json` (a flat string array), same shape as
## gen_sound_category.nim.

import std/syncio
import codegenutil

const OutPath = "src/generated/entity_pose.nim"

proc build(assetsPath: string): string =
  let poses = readStringArray(assetsPath & "/entity_pose.json")

  result = "## GENERATED by src/data_codegen/gen_entity_pose.nim - do not edit by hand.\n\n"
  result.add("type\n  EntityPose* = enum\n")
  for p in poses:
    result.add("    ep" & toPascalCase(p) & "\n")

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
