## Port of tools/codegen/src/game_rules.rs.
##
## Reads `assets/game_rules.json` (a name -> value map where each value is
## either a plain bool, a plain int, or `{"default": int, "min": ..,
## "max": ..}` - only `default` matters here, `min`/`max` aren't used by
## the Rust generator either), sorted by name (`BTreeMap<String, Value>`
## iteration order).
##
## Scope note: upstream's generator also emits a full `GameRuleRegistry`
## struct with serde (de)serialization, a `GameRuleValue<I,B>` enum, and
## `get`/`get_mut` accessors keyed by field mutation - that's a runtime
## storage/registry design, not pure data, and deserves its own decision
## when game rules actually get wired into a world/server type. This
## generator ports the portable data half: the `GameRule` enum plus each
## rule's kind (bool/int) and default value.
##
## Run with `nimony c -r src/data_codegen/gen_game_rules.nim` from the
## minecraft-server repo root.

import std/[syncio, json]
import codegenutil

const OutPath = "src/generated/game_rules.nim"

type
  RuleKind = enum
    rkBool
    rkInt

  RuleEntry = object
    name: string
    kind: RuleKind
    defBool: bool
    defInt: int64

proc manualSortByName(s: var seq[RuleEntry]) =
  ## `algorithm.sort(seq[RuleEntry], proc(a,b): int = ...)` crashes at
  ## C-codegen (not at `nimony check`) when the element type is an object
  ## with an enum field - confirmed via a minimal repro, another variant
  ## of this port's closure-related Nimony compiler bugs. Plain insertion
  ## sort with no closure sidesteps it; 59 entries, performance is moot.
  var i = 1
  while i < s.len:
    var j = i
    while j > 0 and s[j-1].name > s[j].name:
      let tmp = s[j-1]
      s[j-1] = s[j]
      s[j] = tmp
      dec j
    inc i

proc readGameRules(path: string): seq[RuleEntry] =
  var tree = parseFile(path)
  let obj = root(tree)
  result = @[]
  for name, val in obj.pairs():
    var e = RuleEntry(name: name, kind: rkBool, defBool: false, defInt: 0)
    let vk = val.kind
    case vk
    of JBool:
      e.kind = rkBool
      e.defBool = val.getBool()
    of JInt:
      e.kind = rkInt
      e.defInt = val.getInt()
    of JObject:
      e.kind = rkInt
      for k, v in val.pairs():
        if k == "default":
          e.defInt = v.getInt()
    else:
      discard
    result.add(e)
  manualSortByName(result)

proc build(assetsPath: string): string =
  let rules = readGameRules(assetsPath & "/game_rules.json")

  var s = "## GENERATED by src/data_codegen/gen_game_rules.nim - do not edit by hand.\n\n"
  s.add("type\n")
  s.add("  GameRule* = enum\n")
  for r in rules:
    s.add("    gr" & toPascalCase(r.name) & "\n")
  s.add("\n")
  s.add("  GameRuleKind* = enum\n")
  s.add("    grkBool\n")
  s.add("    grkInt\n\n")

  s.add("proc gameRuleName*(r: GameRule): string =\n")
  s.add("  case r\n")
  for r in rules:
    s.add("  of gr" & toPascalCase(r.name) & ": \"" & r.name & "\"\n")
  s.add("\n")

  s.add("proc gameRuleFromName*(name: string): (bool, GameRule) =\n")
  s.add("  case name\n")
  for r in rules:
    s.add("  of \"" & r.name & "\": (true, gr" & toPascalCase(r.name) & ")\n")
  s.add("  else: (false, gr" & toPascalCase(rules[0].name) & ")\n\n")

  s.add("proc gameRuleKind*(r: GameRule): GameRuleKind =\n")
  s.add("  case r\n")
  for r in rules:
    let kindName = if r.kind == rkBool: "grkBool" else: "grkInt"
    s.add("  of gr" & toPascalCase(r.name) & ": " & kindName & "\n")
  s.add("\n")

  s.add("proc defaultBool*(r: GameRule): bool =\n")
  s.add("  ## Meaningful only when `gameRuleKind(r) == grkBool`.\n")
  s.add("  case r\n")
  for r in rules:
    let v = if r.kind == rkBool: $r.defBool else: "false"
    s.add("  of gr" & toPascalCase(r.name) & ": " & v & "\n")
  s.add("\n")

  s.add("proc defaultInt*(r: GameRule): int64 =\n")
  s.add("  ## Meaningful only when `gameRuleKind(r) == grkInt`.\n")
  s.add("  case r\n")
  for r in rules:
    let v = if r.kind == rkInt: $r.defInt else: "0"
    s.add("  of gr" & toPascalCase(r.name) & ": " & v & "'i64\n")
  s.add("\n")

  s.add("proc allGameRules*(): seq[GameRule] =\n")
  s.add("  @[\n")
  for r in rules:
    s.add("    gr" & toPascalCase(r.name) & ",\n")
  s.add("  ]\n")

  s

when isMainModule:
  let assetsPath = "../upstream-ref/assets"
  try:
    let generated = build(assetsPath)
    writeFile(OutPath, generated)
    echo "wrote " & OutPath & " (" & $generated.len & " bytes)"
  except ErrorCode as e:
    echo "generation failed: " & $e
