## Generates src/generated/registry_data.nim: NBT-encoded byte blobs for
## every entry of every "synced registry" (the data Java Edition's
## `minecraft:registry_data` config packet sends to clients - see
## src/protocol/configpackets.nim's `CRegistryData`).
## Port of tools/pumpkin-codegen/src/registry.rs.
##
## Upstream builds a `TokenStream` embedding each entry's NBT bytes as a
## Rust byte-string literal (`b"..."`) inside a `static` table, keyed by
## version (only one version, V_26_3, is actually populated - `get_synced`
## always reads `REGISTRY_V_26_3` regardless of the version argument, so
## this generator does the same: one flat table, no per-version branching).
## This generator does the equivalent for Nimony: walks the same ~31
## `assets/datapack/data/minecraft/<registry>/*.json` directories, converts
## each entry to NBT via jsontonbt.nim, and emits a `seq[byte]` literal per
## entry in a plain Nimony data table.
##
## Run with `nimony c -r src/data_codegen/gen_registry.nim` from the repo
## root.

import std/[syncio, json, paths, dirs]
import jsontonbt
import codegenutil
import "../nbt/tag"
import "../nbt/nbtbase"
import "../nbt/nbtdoc"
import "../nbt/serializer"

const SyncedRegistries = [
  "worldgen/biome", "chat_type", "trim_pattern", "trim_material",
  "wolf_variant", "wolf_sound_variant", "pig_variant", "pig_sound_variant",
  "frog_variant", "cat_variant", "cat_sound_variant", "cow_variant",
  "cow_sound_variant", "chicken_variant", "chicken_sound_variant",
  "zombie_nautilus_variant", "painting_variant", "dimension_type",
  "damage_type", "jukebox_song", "banner_pattern", "instrument",
  "enchantment", "timeline", "dialog", "world_clock", "test_environment",
  "test_instance", "sulfur_cube_archetype", "decorated_pot_pattern",
  "block_transformer", "worldgen/block_state_provider",
]

const AssetsRoot = "../upstream-ref/assets/datapack/data/minecraft"

proc bytesToNimLiteral(b: seq[byte]): string =
  ## Emits `@[1'u8, 2'u8, ...]` - Nimony has no raw byte-string literal
  ## syntax matching Rust's `b"..."`, so this is the direct equivalent.
  result = "@["
  for i, x in b:
    if i > 0: result.add(", ")
    result.add($x)
    result.add("'u8")
  result.add(']')

proc entryBytes(node: JsonNode): seq[byte] =
  ## Mirrors registry.rs: a compound gets written unnamed via Nbt.write;
  ## any other top-level shape (upstream's `other` branch) is serialized
  ## as bare payload data with no type-id/name prefix. Every real registry
  ## entry file here is a JSON object, so the compound path is what always
  ## actually runs; the other branch exists for parity with upstream's
  ## exhaustive match, not because it's expected to fire.
  let tag = jsonToNbtTag(node)
  if tag.kind == ntkCompound:
    let doc = newNbt("", tag.compoundVal)
    writeUnnamed(doc, nwmJava)
  else:
    var w = newNbtWriter(nwmJava)
    discard serializeData(tag, w)
    w.buf

proc rawChatTypeEntry(): JsonNode =
  ## Upstream injects a hardcoded "raw" chat_type entry for vanilla parity
  ## (registry.rs lines 87-92) - not present in any assets/ JSON file.
  var tree = parseJson("""{
    "chat": {"translation_key": "%s", "parameters": ["content"]},
    "narration": {"translation_key": "%s says %s", "parameters": ["sender", "content"]}
  }""")
  root(tree)

proc main() =
  var output = "## Generated by src/data_codegen/gen_registry.nim - do not edit by hand.\n"
  output.add("## NBT-encoded registry entries for the minecraft:registry_data config packet.\n\n")
  output.add("type\n")
  output.add("  RegistryEntry* = object\n")
  output.add("    name*: string\n")
  output.add("    data*: seq[byte]\n\n")
  output.add("  RegistryTable* = object\n")
  output.add("    registryId*: string\n")
  output.add("    entries*: seq[RegistryEntry]\n\n")

  var regCount = 0
  var entryCount = 0
  output.add("let registries*: seq[RegistryTable] = @[\n")
  for regName in SyncedRegistries:
    let dir = path(AssetsRoot & "/" & regName)
    let stems = listJsonStems(dir)
    if stems.len == 0 and regName != "chat_type":
      continue
    inc regCount
    output.add("  RegistryTable(registryId: \"" & regName & "\", entries: @[\n")
    for (stem, path) in stems:
      var tree = parseFile($path)
      let node = root(tree)
      let data = entryBytes(node)
      output.add("    RegistryEntry(name: \"" & stem & "\", data: " & bytesToNimLiteral(data) & "),\n")
      inc entryCount
    if regName == "chat_type":
      let data = entryBytes(rawChatTypeEntry())
      output.add("    RegistryEntry(name: \"raw\", data: " & bytesToNimLiteral(data) & "),\n")
      inc entryCount
    output.add("  ]),\n")
  output.add("]\n")

  try:
    writeFile("src/generated/registry_data.nim", output)
    echo "wrote src/generated/registry_data.nim: ", regCount, " registries, ", entryCount, " entries"
  except ErrorCode as e:
    echo "write failed: " & $e

main()
